CRITICAL - 2022-05-11 10:19:06 --> Undefined variable: userModel
#0 D:\xampp\htdocs\api\app\Controllers\WorkoutController.php(51): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined varia...', 'D:\\xampp\\htdocs...', 51, Array)
#1 D:\xampp\htdocs\api\system\CodeIgniter.php(824): App\Controllers\WorkoutController->getWorkout('12')
#2 D:\xampp\htdocs\api\system\CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\WorkoutController))
#3 D:\xampp\htdocs\api\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 D:\xampp\htdocs\api\index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2022-05-11 10:27:39 --> syntax error, unexpected ';', expecting ']'
#0 D:\xampp\htdocs\api\system\Autoloader\Autoloader.php(241): CodeIgniter\Autoloader\Autoloader->includeFile('D:\\xampp\\htdocs...')
#1 D:\xampp\htdocs\api\system\Autoloader\Autoloader.php(219): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Controllers...')
#2 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Controllers...')
#3 [internal function]: spl_autoload_call('App\\Controllers...')
#4 D:\xampp\htdocs\api\system\CodeIgniter.php(789): class_exists('\\App\\Controller...', true)
#5 D:\xampp\htdocs\api\system\CodeIgniter.php(397): CodeIgniter\CodeIgniter->startController()
#6 D:\xampp\htdocs\api\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\xampp\htdocs\api\index.php(37): CodeIgniter\CodeIgniter->run()
#8 {main}
ERROR - 2022-05-11 10:29:32 --> Unknown column 'id' in 'where clause'
CRITICAL - 2022-05-11 10:29:32 --> Call to a member function getFirstRow() on bool
#0 D:\xampp\htdocs\api\system\BaseModel.php(523): CodeIgniter\Model->doFind(true, 12)
#1 D:\xampp\htdocs\api\app\Controllers\WorkoutController.php(53): CodeIgniter\BaseModel->find(12)
#2 D:\xampp\htdocs\api\system\CodeIgniter.php(824): App\Controllers\WorkoutController->getWorkout(12)
#3 D:\xampp\htdocs\api\system\CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\WorkoutController))
#4 D:\xampp\htdocs\api\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 D:\xampp\htdocs\api\index.php(37): CodeIgniter\CodeIgniter->run()
#6 {main}
CRITICAL - 2022-05-11 10:31:29 --> syntax error, unexpected '*', expecting ']'
#0 D:\xampp\htdocs\api\system\Autoloader\Autoloader.php(241): CodeIgniter\Autoloader\Autoloader->includeFile('D:\\xampp\\htdocs...')
#1 D:\xampp\htdocs\api\system\Autoloader\Autoloader.php(219): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Models\\Work...')
#2 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Models\\Work...')
#3 D:\xampp\htdocs\api\app\Controllers\WorkoutController.php(50): spl_autoload_call('App\\Models\\Work...')
#4 D:\xampp\htdocs\api\system\CodeIgniter.php(824): App\Controllers\WorkoutController->getWorkout('12')
#5 D:\xampp\htdocs\api\system\CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\WorkoutController))
#6 D:\xampp\htdocs\api\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\xampp\htdocs\api\index.php(37): CodeIgniter\CodeIgniter->run()
#8 {main}
ERROR - 2022-05-11 10:31:53 --> Unknown column 'id' in 'where clause'
CRITICAL - 2022-05-11 10:31:53 --> Call to a member function getFirstRow() on bool
#0 D:\xampp\htdocs\api\system\BaseModel.php(523): CodeIgniter\Model->doFind(true, 12)
#1 D:\xampp\htdocs\api\app\Controllers\WorkoutController.php(52): CodeIgniter\BaseModel->find(12)
#2 D:\xampp\htdocs\api\system\CodeIgniter.php(824): App\Controllers\WorkoutController->getWorkout('12')
#3 D:\xampp\htdocs\api\system\CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\WorkoutController))
#4 D:\xampp\htdocs\api\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 D:\xampp\htdocs\api\index.php(37): CodeIgniter\CodeIgniter->run()
#6 {main}
ERROR - 2022-05-11 10:32:11 --> Unknown column 'id' in 'where clause'
CRITICAL - 2022-05-11 10:32:11 --> Call to a member function getFirstRow() on bool
#0 D:\xampp\htdocs\api\system\BaseModel.php(523): CodeIgniter\Model->doFind(true, '12')
#1 D:\xampp\htdocs\api\app\Controllers\WorkoutController.php(52): CodeIgniter\BaseModel->find('12')
#2 D:\xampp\htdocs\api\system\CodeIgniter.php(824): App\Controllers\WorkoutController->getWorkout('12')
#3 D:\xampp\htdocs\api\system\CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\WorkoutController))
#4 D:\xampp\htdocs\api\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 D:\xampp\htdocs\api\index.php(37): CodeIgniter\CodeIgniter->run()
#6 {main}
ERROR - 2022-05-11 10:32:12 --> Unknown column 'id' in 'where clause'
CRITICAL - 2022-05-11 10:32:12 --> Call to a member function getFirstRow() on bool
#0 D:\xampp\htdocs\api\system\BaseModel.php(523): CodeIgniter\Model->doFind(true, '12')
#1 D:\xampp\htdocs\api\app\Controllers\WorkoutController.php(52): CodeIgniter\BaseModel->find('12')
#2 D:\xampp\htdocs\api\system\CodeIgniter.php(824): App\Controllers\WorkoutController->getWorkout('12')
#3 D:\xampp\htdocs\api\system\CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\WorkoutController))
#4 D:\xampp\htdocs\api\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 D:\xampp\htdocs\api\index.php(37): CodeIgniter\CodeIgniter->run()
#6 {main}
CRITICAL - 2022-05-11 10:57:20 --> syntax error, unexpected ';', expecting ']'
#0 D:\xampp\htdocs\api\system\Autoloader\Autoloader.php(241): CodeIgniter\Autoloader\Autoloader->includeFile('D:\\xampp\\htdocs...')
#1 D:\xampp\htdocs\api\system\Autoloader\Autoloader.php(219): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Controllers...')
#2 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Controllers...')
#3 [internal function]: spl_autoload_call('App\\Controllers...')
#4 D:\xampp\htdocs\api\system\CodeIgniter.php(789): class_exists('\\App\\Controller...', true)
#5 D:\xampp\htdocs\api\system\CodeIgniter.php(397): CodeIgniter\CodeIgniter->startController()
#6 D:\xampp\htdocs\api\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\xampp\htdocs\api\index.php(37): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2022-05-11 10:57:39 --> syntax error, unexpected ';', expecting ']'
#0 D:\xampp\htdocs\api\system\Autoloader\Autoloader.php(241): CodeIgniter\Autoloader\Autoloader->includeFile('D:\\xampp\\htdocs...')
#1 D:\xampp\htdocs\api\system\Autoloader\Autoloader.php(219): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Controllers...')
#2 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Controllers...')
#3 [internal function]: spl_autoload_call('App\\Controllers...')
#4 D:\xampp\htdocs\api\system\CodeIgniter.php(789): class_exists('\\App\\Controller...', true)
#5 D:\xampp\htdocs\api\system\CodeIgniter.php(397): CodeIgniter\CodeIgniter->startController()
#6 D:\xampp\htdocs\api\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\xampp\htdocs\api\index.php(37): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2022-05-11 10:57:55 --> syntax error, unexpected '=', expecting ']'
#0 D:\xampp\htdocs\api\system\Autoloader\Autoloader.php(241): CodeIgniter\Autoloader\Autoloader->includeFile('D:\\xampp\\htdocs...')
#1 D:\xampp\htdocs\api\system\Autoloader\Autoloader.php(219): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Controllers...')
#2 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Controllers...')
#3 [internal function]: spl_autoload_call('App\\Controllers...')
#4 D:\xampp\htdocs\api\system\CodeIgniter.php(789): class_exists('\\App\\Controller...', true)
#5 D:\xampp\htdocs\api\system\CodeIgniter.php(397): CodeIgniter\CodeIgniter->startController()
#6 D:\xampp\htdocs\api\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\xampp\htdocs\api\index.php(37): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2022-05-11 10:58:14 --> syntax error, unexpected '=', expecting ']'
#0 D:\xampp\htdocs\api\system\Autoloader\Autoloader.php(241): CodeIgniter\Autoloader\Autoloader->includeFile('D:\\xampp\\htdocs...')
#1 D:\xampp\htdocs\api\system\Autoloader\Autoloader.php(219): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Controllers...')
#2 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Controllers...')
#3 [internal function]: spl_autoload_call('App\\Controllers...')
#4 D:\xampp\htdocs\api\system\CodeIgniter.php(789): class_exists('\\App\\Controller...', true)
#5 D:\xampp\htdocs\api\system\CodeIgniter.php(397): CodeIgniter\CodeIgniter->startController()
#6 D:\xampp\htdocs\api\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\xampp\htdocs\api\index.php(37): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2022-05-11 10:58:30 --> syntax error, unexpected '=', expecting ']'
#0 D:\xampp\htdocs\api\system\Autoloader\Autoloader.php(241): CodeIgniter\Autoloader\Autoloader->includeFile('D:\\xampp\\htdocs...')
#1 D:\xampp\htdocs\api\system\Autoloader\Autoloader.php(219): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Controllers...')
#2 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Controllers...')
#3 [internal function]: spl_autoload_call('App\\Controllers...')
#4 D:\xampp\htdocs\api\system\CodeIgniter.php(789): class_exists('\\App\\Controller...', true)
#5 D:\xampp\htdocs\api\system\CodeIgniter.php(397): CodeIgniter\CodeIgniter->startController()
#6 D:\xampp\htdocs\api\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\xampp\htdocs\api\index.php(37): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2022-05-11 10:58:47 --> syntax error, unexpected '=', expecting ']'
#0 D:\xampp\htdocs\api\system\Autoloader\Autoloader.php(241): CodeIgniter\Autoloader\Autoloader->includeFile('D:\\xampp\\htdocs...')
#1 D:\xampp\htdocs\api\system\Autoloader\Autoloader.php(219): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Controllers...')
#2 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Controllers...')
#3 [internal function]: spl_autoload_call('App\\Controllers...')
#4 D:\xampp\htdocs\api\system\CodeIgniter.php(789): class_exists('\\App\\Controller...', true)
#5 D:\xampp\htdocs\api\system\CodeIgniter.php(397): CodeIgniter\CodeIgniter->startController()
#6 D:\xampp\htdocs\api\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\xampp\htdocs\api\index.php(37): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2022-05-11 11:37:00 --> Class 'App\Models\MeditationAppModel' not found
#0 D:\xampp\htdocs\api\system\CodeIgniter.php(824): App\Controllers\MeditationDataController->getMeditationApps()
#1 D:\xampp\htdocs\api\system\CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\MeditationDataController))
#2 D:\xampp\htdocs\api\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 D:\xampp\htdocs\api\index.php(37): CodeIgniter\CodeIgniter->run()
#4 {main}
CRITICAL - 2022-05-11 12:45:33 --> There is no data to update.
#0 D:\xampp\htdocs\api\system\BaseModel.php(1574): CodeIgniter\Database\Exceptions\DataException::forEmptyDataset('update')
#1 D:\xampp\htdocs\api\system\BaseModel.php(832): CodeIgniter\BaseModel->transformDataToArray(NULL, 'update')
#2 D:\xampp\htdocs\api\system\Model.php(646): CodeIgniter\BaseModel->update(Array, NULL)
#3 D:\xampp\htdocs\api\app\Controllers\WorkoutController.php(27): CodeIgniter\Model->update(Array)
#4 D:\xampp\htdocs\api\system\CodeIgniter.php(824): App\Controllers\WorkoutController->putWorkout()
#5 D:\xampp\htdocs\api\system\CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\WorkoutController))
#6 D:\xampp\htdocs\api\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\xampp\htdocs\api\index.php(37): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2022-05-11 12:46:12 --> Return value of CodeIgniter\BaseModel::transformDataToArray() must be of the type array, string returned
#0 D:\xampp\htdocs\api\system\BaseModel.php(832): CodeIgniter\BaseModel->transformDataToArray('12', 'update')
#1 D:\xampp\htdocs\api\system\Model.php(646): CodeIgniter\BaseModel->update(Array, '12')
#2 D:\xampp\htdocs\api\app\Controllers\WorkoutController.php(27): CodeIgniter\Model->update(Array, '12')
#3 D:\xampp\htdocs\api\system\CodeIgniter.php(824): App\Controllers\WorkoutController->putWorkout()
#4 D:\xampp\htdocs\api\system\CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\WorkoutController))
#5 D:\xampp\htdocs\api\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 D:\xampp\htdocs\api\index.php(37): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2022-05-11 12:46:22 --> There is no data to update.
#0 D:\xampp\htdocs\api\system\BaseModel.php(1574): CodeIgniter\Database\Exceptions\DataException::forEmptyDataset('update')
#1 D:\xampp\htdocs\api\system\BaseModel.php(832): CodeIgniter\BaseModel->transformDataToArray(NULL, 'update')
#2 D:\xampp\htdocs\api\system\Model.php(646): CodeIgniter\BaseModel->update(Array, NULL)
#3 D:\xampp\htdocs\api\app\Controllers\WorkoutController.php(27): CodeIgniter\Model->update(Array, NULL)
#4 D:\xampp\htdocs\api\system\CodeIgniter.php(824): App\Controllers\WorkoutController->putWorkout()
#5 D:\xampp\htdocs\api\system\CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\WorkoutController))
#6 D:\xampp\htdocs\api\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\xampp\htdocs\api\index.php(37): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2022-05-11 13:01:38 --> There is no data to update.
#0 D:\xampp\htdocs\api\system\BaseModel.php(1574): CodeIgniter\Database\Exceptions\DataException::forEmptyDataset('update')
#1 D:\xampp\htdocs\api\system\BaseModel.php(832): CodeIgniter\BaseModel->transformDataToArray(NULL, 'update')
#2 D:\xampp\htdocs\api\system\Model.php(646): CodeIgniter\BaseModel->update(Array, NULL)
#3 D:\xampp\htdocs\api\app\Controllers\WorkoutController.php(25): CodeIgniter\Model->update(Array)
#4 D:\xampp\htdocs\api\system\CodeIgniter.php(824): App\Controllers\WorkoutController->putWorkout()
#5 D:\xampp\htdocs\api\system\CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\WorkoutController))
#6 D:\xampp\htdocs\api\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\xampp\htdocs\api\index.php(37): CodeIgniter\CodeIgniter->run()
#8 {main}
ERROR - 2022-05-11 13:01:50 --> Unknown column 'id' in 'where clause'
CRITICAL - 2022-05-11 13:02:53 --> There is no data to update.
#0 D:\xampp\htdocs\api\system\BaseModel.php(1574): CodeIgniter\Database\Exceptions\DataException::forEmptyDataset('update')
#1 D:\xampp\htdocs\api\system\BaseModel.php(832): CodeIgniter\BaseModel->transformDataToArray(NULL, 'update')
#2 D:\xampp\htdocs\api\system\Model.php(646): CodeIgniter\BaseModel->update(Array, NULL)
#3 D:\xampp\htdocs\api\app\Controllers\WorkoutController.php(25): CodeIgniter\Model->update(Array)
#4 D:\xampp\htdocs\api\system\CodeIgniter.php(824): App\Controllers\WorkoutController->putWorkout()
#5 D:\xampp\htdocs\api\system\CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\WorkoutController))
#6 D:\xampp\htdocs\api\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\xampp\htdocs\api\index.php(37): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2022-05-11 13:04:15 --> There is no data to update.
#0 D:\xampp\htdocs\api\system\BaseModel.php(1574): CodeIgniter\Database\Exceptions\DataException::forEmptyDataset('update')
#1 D:\xampp\htdocs\api\system\BaseModel.php(832): CodeIgniter\BaseModel->transformDataToArray(NULL, 'update')
#2 D:\xampp\htdocs\api\system\Model.php(646): CodeIgniter\BaseModel->update(Array, NULL)
#3 D:\xampp\htdocs\api\app\Controllers\WorkoutController.php(26): CodeIgniter\Model->update(Array)
#4 D:\xampp\htdocs\api\system\CodeIgniter.php(824): App\Controllers\WorkoutController->putWorkout()
#5 D:\xampp\htdocs\api\system\CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\WorkoutController))
#6 D:\xampp\htdocs\api\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\xampp\htdocs\api\index.php(37): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2022-05-11 13:07:39 --> Allowed fields must be specified for model: App\Models\WorkoutModel
#0 D:\xampp\htdocs\api\system\BaseModel.php(1138): CodeIgniter\Database\Exceptions\DataException::forInvalidAllowedFields('App\\Models\\Work...')
#1 D:\xampp\htdocs\api\system\BaseModel.php(841): CodeIgniter\BaseModel->doProtectFields(Array)
#2 D:\xampp\htdocs\api\system\Model.php(646): CodeIgniter\BaseModel->update(Array, Array)
#3 D:\xampp\htdocs\api\app\Controllers\WorkoutController.php(25): CodeIgniter\Model->update(Array)
#4 D:\xampp\htdocs\api\system\CodeIgniter.php(824): App\Controllers\WorkoutController->putWorkout()
#5 D:\xampp\htdocs\api\system\CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\WorkoutController))
#6 D:\xampp\htdocs\api\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\xampp\htdocs\api\index.php(37): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2022-05-11 13:07:59 --> There is no data to update.
#0 D:\xampp\htdocs\api\system\BaseModel.php(846): CodeIgniter\Database\Exceptions\DataException::forEmptyDataset('update')
#1 D:\xampp\htdocs\api\system\Model.php(646): CodeIgniter\BaseModel->update(Array, Array)
#2 D:\xampp\htdocs\api\app\Controllers\WorkoutController.php(25): CodeIgniter\Model->update(Array)
#3 D:\xampp\htdocs\api\system\CodeIgniter.php(824): App\Controllers\WorkoutController->putWorkout()
#4 D:\xampp\htdocs\api\system\CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\WorkoutController))
#5 D:\xampp\htdocs\api\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 D:\xampp\htdocs\api\index.php(37): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2022-05-11 13:08:36 --> There is no data to update.
#0 D:\xampp\htdocs\api\system\BaseModel.php(846): CodeIgniter\Database\Exceptions\DataException::forEmptyDataset('update')
#1 D:\xampp\htdocs\api\system\Model.php(646): CodeIgniter\BaseModel->update(NULL, Array)
#2 D:\xampp\htdocs\api\app\Controllers\WorkoutController.php(25): CodeIgniter\Model->update()
#3 D:\xampp\htdocs\api\system\CodeIgniter.php(824): App\Controllers\WorkoutController->putWorkout()
#4 D:\xampp\htdocs\api\system\CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\WorkoutController))
#5 D:\xampp\htdocs\api\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 D:\xampp\htdocs\api\index.php(37): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2022-05-11 13:11:58 --> syntax error, unexpected '$rs' (T_VARIABLE)
#0 D:\xampp\htdocs\api\system\Autoloader\Autoloader.php(241): CodeIgniter\Autoloader\Autoloader->includeFile('D:\\xampp\\htdocs...')
#1 D:\xampp\htdocs\api\system\Autoloader\Autoloader.php(219): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Controllers...')
#2 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Controllers...')
#3 [internal function]: spl_autoload_call('App\\Controllers...')
#4 D:\xampp\htdocs\api\system\CodeIgniter.php(789): class_exists('\\App\\Controller...', true)
#5 D:\xampp\htdocs\api\system\CodeIgniter.php(397): CodeIgniter\CodeIgniter->startController()
#6 D:\xampp\htdocs\api\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\xampp\htdocs\api\index.php(37): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2022-05-11 13:12:01 --> syntax error, unexpected '$rs' (T_VARIABLE)
#0 D:\xampp\htdocs\api\system\Autoloader\Autoloader.php(241): CodeIgniter\Autoloader\Autoloader->includeFile('D:\\xampp\\htdocs...')
#1 D:\xampp\htdocs\api\system\Autoloader\Autoloader.php(219): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Controllers...')
#2 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Controllers...')
#3 [internal function]: spl_autoload_call('App\\Controllers...')
#4 D:\xampp\htdocs\api\system\CodeIgniter.php(789): class_exists('\\App\\Controller...', true)
#5 D:\xampp\htdocs\api\system\CodeIgniter.php(397): CodeIgniter\CodeIgniter->startController()
#6 D:\xampp\htdocs\api\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\xampp\htdocs\api\index.php(37): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2022-05-11 13:12:58 --> syntax error, unexpected '$rs' (T_VARIABLE)
#0 D:\xampp\htdocs\api\system\Autoloader\Autoloader.php(241): CodeIgniter\Autoloader\Autoloader->includeFile('D:\\xampp\\htdocs...')
#1 D:\xampp\htdocs\api\system\Autoloader\Autoloader.php(219): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Controllers...')
#2 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Controllers...')
#3 [internal function]: spl_autoload_call('App\\Controllers...')
#4 D:\xampp\htdocs\api\system\CodeIgniter.php(789): class_exists('\\App\\Controller...', true)
#5 D:\xampp\htdocs\api\system\CodeIgniter.php(397): CodeIgniter\CodeIgniter->startController()
#6 D:\xampp\htdocs\api\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\xampp\htdocs\api\index.php(37): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2022-05-11 13:13:00 --> syntax error, unexpected '$rs' (T_VARIABLE)
#0 D:\xampp\htdocs\api\system\Autoloader\Autoloader.php(241): CodeIgniter\Autoloader\Autoloader->includeFile('D:\\xampp\\htdocs...')
#1 D:\xampp\htdocs\api\system\Autoloader\Autoloader.php(219): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Controllers...')
#2 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Controllers...')
#3 [internal function]: spl_autoload_call('App\\Controllers...')
#4 D:\xampp\htdocs\api\system\CodeIgniter.php(789): class_exists('\\App\\Controller...', true)
#5 D:\xampp\htdocs\api\system\CodeIgniter.php(397): CodeIgniter\CodeIgniter->startController()
#6 D:\xampp\htdocs\api\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\xampp\htdocs\api\index.php(37): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2022-05-11 13:13:33 --> syntax error, unexpected '$rs' (T_VARIABLE)
#0 D:\xampp\htdocs\api\system\Autoloader\Autoloader.php(241): CodeIgniter\Autoloader\Autoloader->includeFile('D:\\xampp\\htdocs...')
#1 D:\xampp\htdocs\api\system\Autoloader\Autoloader.php(219): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Controllers...')
#2 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Controllers...')
#3 [internal function]: spl_autoload_call('App\\Controllers...')
#4 D:\xampp\htdocs\api\system\CodeIgniter.php(789): class_exists('\\App\\Controller...', true)
#5 D:\xampp\htdocs\api\system\CodeIgniter.php(397): CodeIgniter\CodeIgniter->startController()
#6 D:\xampp\htdocs\api\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\xampp\htdocs\api\index.php(37): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2022-05-11 13:14:05 --> syntax error, unexpected '$rs' (T_VARIABLE)
#0 D:\xampp\htdocs\api\system\Autoloader\Autoloader.php(241): CodeIgniter\Autoloader\Autoloader->includeFile('D:\\xampp\\htdocs...')
#1 D:\xampp\htdocs\api\system\Autoloader\Autoloader.php(219): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Controllers...')
#2 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Controllers...')
#3 [internal function]: spl_autoload_call('App\\Controllers...')
#4 D:\xampp\htdocs\api\system\CodeIgniter.php(789): class_exists('\\App\\Controller...', true)
#5 D:\xampp\htdocs\api\system\CodeIgniter.php(397): CodeIgniter\CodeIgniter->startController()
#6 D:\xampp\htdocs\api\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\xampp\htdocs\api\index.php(37): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2022-05-11 13:14:49 --> syntax error, unexpected '=>' (T_DOUBLE_ARROW)
#0 D:\xampp\htdocs\api\system\Autoloader\Autoloader.php(241): CodeIgniter\Autoloader\Autoloader->includeFile('D:\\xampp\\htdocs...')
#1 D:\xampp\htdocs\api\system\Autoloader\Autoloader.php(219): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Controllers...')
#2 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Controllers...')
#3 [internal function]: spl_autoload_call('App\\Controllers...')
#4 D:\xampp\htdocs\api\system\CodeIgniter.php(789): class_exists('\\App\\Controller...', true)
#5 D:\xampp\htdocs\api\system\CodeIgniter.php(397): CodeIgniter\CodeIgniter->startController()
#6 D:\xampp\htdocs\api\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\xampp\htdocs\api\index.php(37): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2022-05-11 13:15:05 --> syntax error, unexpected '=>' (T_DOUBLE_ARROW)
#0 D:\xampp\htdocs\api\system\Autoloader\Autoloader.php(241): CodeIgniter\Autoloader\Autoloader->includeFile('D:\\xampp\\htdocs...')
#1 D:\xampp\htdocs\api\system\Autoloader\Autoloader.php(219): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Controllers...')
#2 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Controllers...')
#3 [internal function]: spl_autoload_call('App\\Controllers...')
#4 D:\xampp\htdocs\api\system\CodeIgniter.php(789): class_exists('\\App\\Controller...', true)
#5 D:\xampp\htdocs\api\system\CodeIgniter.php(397): CodeIgniter\CodeIgniter->startController()
#6 D:\xampp\htdocs\api\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\xampp\htdocs\api\index.php(37): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2022-05-11 13:15:15 --> syntax error, unexpected '=>' (T_DOUBLE_ARROW)
#0 D:\xampp\htdocs\api\system\Autoloader\Autoloader.php(241): CodeIgniter\Autoloader\Autoloader->includeFile('D:\\xampp\\htdocs...')
#1 D:\xampp\htdocs\api\system\Autoloader\Autoloader.php(219): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Controllers...')
#2 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Controllers...')
#3 [internal function]: spl_autoload_call('App\\Controllers...')
#4 D:\xampp\htdocs\api\system\CodeIgniter.php(789): class_exists('\\App\\Controller...', true)
#5 D:\xampp\htdocs\api\system\CodeIgniter.php(397): CodeIgniter\CodeIgniter->startController()
#6 D:\xampp\htdocs\api\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\xampp\htdocs\api\index.php(37): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2022-05-11 13:16:06 --> syntax error, unexpected '=>' (T_DOUBLE_ARROW)
#0 D:\xampp\htdocs\api\system\Autoloader\Autoloader.php(241): CodeIgniter\Autoloader\Autoloader->includeFile('D:\\xampp\\htdocs...')
#1 D:\xampp\htdocs\api\system\Autoloader\Autoloader.php(219): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Controllers...')
#2 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Controllers...')
#3 [internal function]: spl_autoload_call('App\\Controllers...')
#4 D:\xampp\htdocs\api\system\CodeIgniter.php(789): class_exists('\\App\\Controller...', true)
#5 D:\xampp\htdocs\api\system\CodeIgniter.php(397): CodeIgniter\CodeIgniter->startController()
#6 D:\xampp\htdocs\api\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\xampp\htdocs\api\index.php(37): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2022-05-11 13:16:44 --> syntax error, unexpected '=>' (T_DOUBLE_ARROW)
#0 D:\xampp\htdocs\api\system\Autoloader\Autoloader.php(241): CodeIgniter\Autoloader\Autoloader->includeFile('D:\\xampp\\htdocs...')
#1 D:\xampp\htdocs\api\system\Autoloader\Autoloader.php(219): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Controllers...')
#2 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Controllers...')
#3 [internal function]: spl_autoload_call('App\\Controllers...')
#4 D:\xampp\htdocs\api\system\CodeIgniter.php(789): class_exists('\\App\\Controller...', true)
#5 D:\xampp\htdocs\api\system\CodeIgniter.php(397): CodeIgniter\CodeIgniter->startController()
#6 D:\xampp\htdocs\api\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\xampp\htdocs\api\index.php(37): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2022-05-11 13:28:27 --> There is no data to update.
#0 D:\xampp\htdocs\api\system\BaseModel.php(846): CodeIgniter\Database\Exceptions\DataException::forEmptyDataset('update')
#1 D:\xampp\htdocs\api\system\Model.php(646): CodeIgniter\BaseModel->update(Array, Array)
#2 D:\xampp\htdocs\api\app\Controllers\WorkoutController.php(25): CodeIgniter\Model->update('12', Array)
#3 D:\xampp\htdocs\api\system\CodeIgniter.php(824): App\Controllers\WorkoutController->putWorkout()
#4 D:\xampp\htdocs\api\system\CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\WorkoutController))
#5 D:\xampp\htdocs\api\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 D:\xampp\htdocs\api\index.php(37): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2022-05-11 13:49:49 --> syntax error, unexpected '}'
#0 D:\xampp\htdocs\api\system\Autoloader\Autoloader.php(241): CodeIgniter\Autoloader\Autoloader->includeFile('D:\\xampp\\htdocs...')
#1 D:\xampp\htdocs\api\system\Autoloader\Autoloader.php(219): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Controllers...')
#2 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Controllers...')
#3 [internal function]: spl_autoload_call('App\\Controllers...')
#4 D:\xampp\htdocs\api\system\CodeIgniter.php(789): class_exists('\\App\\Controller...', true)
#5 D:\xampp\htdocs\api\system\CodeIgniter.php(397): CodeIgniter\CodeIgniter->startController()
#6 D:\xampp\htdocs\api\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\xampp\htdocs\api\index.php(37): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2022-05-11 13:50:06 --> syntax error, unexpected '}'
#0 D:\xampp\htdocs\api\system\Autoloader\Autoloader.php(241): CodeIgniter\Autoloader\Autoloader->includeFile('D:\\xampp\\htdocs...')
#1 D:\xampp\htdocs\api\system\Autoloader\Autoloader.php(219): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Controllers...')
#2 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Controllers...')
#3 [internal function]: spl_autoload_call('App\\Controllers...')
#4 D:\xampp\htdocs\api\system\CodeIgniter.php(789): class_exists('\\App\\Controller...', true)
#5 D:\xampp\htdocs\api\system\CodeIgniter.php(397): CodeIgniter\CodeIgniter->startController()
#6 D:\xampp\htdocs\api\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\xampp\htdocs\api\index.php(37): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2022-05-11 13:50:19 --> syntax error, unexpected '}'
#0 D:\xampp\htdocs\api\system\Autoloader\Autoloader.php(241): CodeIgniter\Autoloader\Autoloader->includeFile('D:\\xampp\\htdocs...')
#1 D:\xampp\htdocs\api\system\Autoloader\Autoloader.php(219): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Controllers...')
#2 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Controllers...')
#3 [internal function]: spl_autoload_call('App\\Controllers...')
#4 D:\xampp\htdocs\api\system\CodeIgniter.php(789): class_exists('\\App\\Controller...', true)
#5 D:\xampp\htdocs\api\system\CodeIgniter.php(397): CodeIgniter\CodeIgniter->startController()
#6 D:\xampp\htdocs\api\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\xampp\htdocs\api\index.php(37): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2022-05-11 13:50:37 --> syntax error, unexpected '}'
#0 D:\xampp\htdocs\api\system\Autoloader\Autoloader.php(241): CodeIgniter\Autoloader\Autoloader->includeFile('D:\\xampp\\htdocs...')
#1 D:\xampp\htdocs\api\system\Autoloader\Autoloader.php(219): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Controllers...')
#2 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Controllers...')
#3 [internal function]: spl_autoload_call('App\\Controllers...')
#4 D:\xampp\htdocs\api\system\CodeIgniter.php(789): class_exists('\\App\\Controller...', true)
#5 D:\xampp\htdocs\api\system\CodeIgniter.php(397): CodeIgniter\CodeIgniter->startController()
#6 D:\xampp\htdocs\api\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\xampp\htdocs\api\index.php(37): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2022-05-11 13:51:08 --> syntax error, unexpected '}'
#0 D:\xampp\htdocs\api\system\Autoloader\Autoloader.php(241): CodeIgniter\Autoloader\Autoloader->includeFile('D:\\xampp\\htdocs...')
#1 D:\xampp\htdocs\api\system\Autoloader\Autoloader.php(219): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Controllers...')
#2 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Controllers...')
#3 [internal function]: spl_autoload_call('App\\Controllers...')
#4 D:\xampp\htdocs\api\system\CodeIgniter.php(789): class_exists('\\App\\Controller...', true)
#5 D:\xampp\htdocs\api\system\CodeIgniter.php(397): CodeIgniter\CodeIgniter->startController()
#6 D:\xampp\htdocs\api\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\xampp\htdocs\api\index.php(37): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2022-05-11 13:51:56 --> syntax error, unexpected '}'
#0 D:\xampp\htdocs\api\system\Autoloader\Autoloader.php(241): CodeIgniter\Autoloader\Autoloader->includeFile('D:\\xampp\\htdocs...')
#1 D:\xampp\htdocs\api\system\Autoloader\Autoloader.php(219): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Controllers...')
#2 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Controllers...')
#3 [internal function]: spl_autoload_call('App\\Controllers...')
#4 D:\xampp\htdocs\api\system\CodeIgniter.php(789): class_exists('\\App\\Controller...', true)
#5 D:\xampp\htdocs\api\system\CodeIgniter.php(397): CodeIgniter\CodeIgniter->startController()
#6 D:\xampp\htdocs\api\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\xampp\htdocs\api\index.php(37): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2022-05-11 14:41:57 --> syntax error, unexpected '}'
#0 D:\xampp\htdocs\api\system\Autoloader\Autoloader.php(241): CodeIgniter\Autoloader\Autoloader->includeFile('D:\\xampp\\htdocs...')
#1 D:\xampp\htdocs\api\system\Autoloader\Autoloader.php(219): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Controllers...')
#2 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Controllers...')
#3 [internal function]: spl_autoload_call('App\\Controllers...')
#4 D:\xampp\htdocs\api\system\CodeIgniter.php(789): class_exists('\\App\\Controller...', true)
#5 D:\xampp\htdocs\api\system\CodeIgniter.php(397): CodeIgniter\CodeIgniter->startController()
#6 D:\xampp\htdocs\api\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\xampp\htdocs\api\index.php(37): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2022-05-11 14:48:06 --> syntax error, unexpected ';', expecting ']'
#0 D:\xampp\htdocs\api\system\Autoloader\Autoloader.php(241): CodeIgniter\Autoloader\Autoloader->includeFile('D:\\xampp\\htdocs...')
#1 D:\xampp\htdocs\api\system\Autoloader\Autoloader.php(219): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Controllers...')
#2 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Controllers...')
#3 [internal function]: spl_autoload_call('App\\Controllers...')
#4 D:\xampp\htdocs\api\system\CodeIgniter.php(789): class_exists('\\App\\Controller...', true)
#5 D:\xampp\htdocs\api\system\CodeIgniter.php(397): CodeIgniter\CodeIgniter->startController()
#6 D:\xampp\htdocs\api\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\xampp\htdocs\api\index.php(37): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2022-05-11 14:48:13 --> syntax error, unexpected ';', expecting ']'
#0 D:\xampp\htdocs\api\system\Autoloader\Autoloader.php(241): CodeIgniter\Autoloader\Autoloader->includeFile('D:\\xampp\\htdocs...')
#1 D:\xampp\htdocs\api\system\Autoloader\Autoloader.php(219): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Controllers...')
#2 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Controllers...')
#3 [internal function]: spl_autoload_call('App\\Controllers...')
#4 D:\xampp\htdocs\api\system\CodeIgniter.php(789): class_exists('\\App\\Controller...', true)
#5 D:\xampp\htdocs\api\system\CodeIgniter.php(397): CodeIgniter\CodeIgniter->startController()
#6 D:\xampp\htdocs\api\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\xampp\htdocs\api\index.php(37): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2022-05-11 14:55:51 --> Call to undefined method App\Models\WorkoutModel::updateone
#0 D:\xampp\htdocs\api\app\Controllers\WorkoutController.php(25): CodeIgniter\Model->__call('updateone', Array)
#1 D:\xampp\htdocs\api\system\CodeIgniter.php(824): App\Controllers\WorkoutController->putWorkout('5')
#2 D:\xampp\htdocs\api\system\CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\WorkoutController))
#3 D:\xampp\htdocs\api\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 D:\xampp\htdocs\api\index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2022-05-11 14:56:05 --> Call to undefined method App\Models\WorkoutModel::updateone
#0 D:\xampp\htdocs\api\app\Controllers\WorkoutController.php(25): CodeIgniter\Model->__call('updateone', Array)
#1 D:\xampp\htdocs\api\system\CodeIgniter.php(824): App\Controllers\WorkoutController->putWorkout('12')
#2 D:\xampp\htdocs\api\system\CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\WorkoutController))
#3 D:\xampp\htdocs\api\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 D:\xampp\htdocs\api\index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2022-05-11 14:57:25 --> Call to undefined method App\Models\WorkoutModel::putWorkout
#0 D:\xampp\htdocs\api\app\Controllers\WorkoutController.php(25): CodeIgniter\Model->__call('putWorkout', Array)
#1 D:\xampp\htdocs\api\system\CodeIgniter.php(824): App\Controllers\WorkoutController->putWorkout('12')
#2 D:\xampp\htdocs\api\system\CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\WorkoutController))
#3 D:\xampp\htdocs\api\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 D:\xampp\htdocs\api\index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2022-05-11 14:57:44 --> Call to undefined method App\Models\WorkoutModel::putWorkout
#0 D:\xampp\htdocs\api\app\Controllers\WorkoutController.php(25): CodeIgniter\Model->__call('putWorkout', Array)
#1 D:\xampp\htdocs\api\system\CodeIgniter.php(824): App\Controllers\WorkoutController->putWorkout('12')
#2 D:\xampp\htdocs\api\system\CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\WorkoutController))
#3 D:\xampp\htdocs\api\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 D:\xampp\htdocs\api\index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2022-05-11 14:58:03 --> Call to undefined method App\Models\WorkoutModel::updateone
#0 D:\xampp\htdocs\api\app\Controllers\WorkoutController.php(25): CodeIgniter\Model->__call('updateone', Array)
#1 D:\xampp\htdocs\api\system\CodeIgniter.php(824): App\Controllers\WorkoutController->putWorkout('12')
#2 D:\xampp\htdocs\api\system\CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\WorkoutController))
#3 D:\xampp\htdocs\api\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 D:\xampp\htdocs\api\index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2022-05-11 14:58:40 --> Call to undefined method App\Models\WorkoutModel::updateone
#0 D:\xampp\htdocs\api\app\Controllers\WorkoutController.php(25): CodeIgniter\Model->__call('updateone', Array)
#1 D:\xampp\htdocs\api\system\CodeIgniter.php(824): App\Controllers\WorkoutController->putWorkout('12')
#2 D:\xampp\htdocs\api\system\CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\WorkoutController))
#3 D:\xampp\htdocs\api\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 D:\xampp\htdocs\api\index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2022-05-11 14:58:45 --> Call to undefined method App\Models\WorkoutModel::updateone
#0 D:\xampp\htdocs\api\app\Controllers\WorkoutController.php(25): CodeIgniter\Model->__call('updateone', Array)
#1 D:\xampp\htdocs\api\system\CodeIgniter.php(824): App\Controllers\WorkoutController->putWorkout('12')
#2 D:\xampp\htdocs\api\system\CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\WorkoutController))
#3 D:\xampp\htdocs\api\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 D:\xampp\htdocs\api\index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2022-05-11 14:58:54 --> Call to undefined method App\Models\WorkoutModel::updateone
#0 D:\xampp\htdocs\api\app\Controllers\WorkoutController.php(25): CodeIgniter\Model->__call('updateone', Array)
#1 D:\xampp\htdocs\api\system\CodeIgniter.php(824): App\Controllers\WorkoutController->putWorkout('12')
#2 D:\xampp\htdocs\api\system\CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\WorkoutController))
#3 D:\xampp\htdocs\api\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 D:\xampp\htdocs\api\index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2022-05-11 15:09:27 --> Cannot use object of type App\Models\WorkoutModel as array
#0 D:\xampp\htdocs\api\system\CodeIgniter.php(824): App\Controllers\WorkoutController->putWorkout('12')
#1 D:\xampp\htdocs\api\system\CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\WorkoutController))
#2 D:\xampp\htdocs\api\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 D:\xampp\htdocs\api\index.php(37): CodeIgniter\CodeIgniter->run()
#4 {main}
CRITICAL - 2022-05-11 15:11:21 --> Array to string conversion
#0 D:\xampp\htdocs\api\app\Controllers\WorkoutController.php(27): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Array to string...', 'D:\\xampp\\htdocs...', 27, Array)
#1 D:\xampp\htdocs\api\system\CodeIgniter.php(824): App\Controllers\WorkoutController->putWorkout('12')
#2 D:\xampp\htdocs\api\system\CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\WorkoutController))
#3 D:\xampp\htdocs\api\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 D:\xampp\htdocs\api\index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2022-05-11 15:20:46 --> syntax error, unexpected '=', expecting ']'
#0 D:\xampp\htdocs\api\system\Autoloader\Autoloader.php(241): CodeIgniter\Autoloader\Autoloader->includeFile('D:\\xampp\\htdocs...')
#1 D:\xampp\htdocs\api\system\Autoloader\Autoloader.php(219): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Controllers...')
#2 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Controllers...')
#3 [internal function]: spl_autoload_call('App\\Controllers...')
#4 D:\xampp\htdocs\api\system\CodeIgniter.php(789): class_exists('\\App\\Controller...', true)
#5 D:\xampp\htdocs\api\system\CodeIgniter.php(397): CodeIgniter\CodeIgniter->startController()
#6 D:\xampp\htdocs\api\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\xampp\htdocs\api\index.php(37): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2022-05-11 15:21:31 --> syntax error, unexpected '=', expecting ']'
#0 D:\xampp\htdocs\api\system\Autoloader\Autoloader.php(241): CodeIgniter\Autoloader\Autoloader->includeFile('D:\\xampp\\htdocs...')
#1 D:\xampp\htdocs\api\system\Autoloader\Autoloader.php(219): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Controllers...')
#2 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Controllers...')
#3 [internal function]: spl_autoload_call('App\\Controllers...')
#4 D:\xampp\htdocs\api\system\CodeIgniter.php(789): class_exists('\\App\\Controller...', true)
#5 D:\xampp\htdocs\api\system\CodeIgniter.php(397): CodeIgniter\CodeIgniter->startController()
#6 D:\xampp\htdocs\api\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\xampp\htdocs\api\index.php(37): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2022-05-11 15:22:01 --> syntax error, unexpected '=', expecting ']'
#0 D:\xampp\htdocs\api\system\Autoloader\Autoloader.php(241): CodeIgniter\Autoloader\Autoloader->includeFile('D:\\xampp\\htdocs...')
#1 D:\xampp\htdocs\api\system\Autoloader\Autoloader.php(219): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Controllers...')
#2 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Controllers...')
#3 [internal function]: spl_autoload_call('App\\Controllers...')
#4 D:\xampp\htdocs\api\system\CodeIgniter.php(789): class_exists('\\App\\Controller...', true)
#5 D:\xampp\htdocs\api\system\CodeIgniter.php(397): CodeIgniter\CodeIgniter->startController()
#6 D:\xampp\htdocs\api\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\xampp\htdocs\api\index.php(37): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2022-05-11 15:27:36 --> Undefined property: App\Controllers\WorkoutController::$db
#0 D:\xampp\htdocs\api\app\Controllers\WorkoutController.php(22): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined prope...', 'D:\\xampp\\htdocs...', 22, Array)
#1 D:\xampp\htdocs\api\system\CodeIgniter.php(824): App\Controllers\WorkoutController->putWorkout('12')
#2 D:\xampp\htdocs\api\system\CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\WorkoutController))
#3 D:\xampp\htdocs\api\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 D:\xampp\htdocs\api\index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2022-05-11 15:27:55 --> Undefined property: App\Controllers\WorkoutController::$db
#0 D:\xampp\htdocs\api\app\Controllers\WorkoutController.php(22): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined prope...', 'D:\\xampp\\htdocs...', 22, Array)
#1 D:\xampp\htdocs\api\system\CodeIgniter.php(824): App\Controllers\WorkoutController->putWorkout('12')
#2 D:\xampp\htdocs\api\system\CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\WorkoutController))
#3 D:\xampp\htdocs\api\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 D:\xampp\htdocs\api\index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2022-05-11 15:28:26 --> Undefined property: App\Controllers\WorkoutController::$db
#0 D:\xampp\htdocs\api\app\Controllers\WorkoutController.php(22): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined prope...', 'D:\\xampp\\htdocs...', 22, Array)
#1 D:\xampp\htdocs\api\system\CodeIgniter.php(824): App\Controllers\WorkoutController->putWorkout('12')
#2 D:\xampp\htdocs\api\system\CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\WorkoutController))
#3 D:\xampp\htdocs\api\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 D:\xampp\htdocs\api\index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2022-05-11 15:29:57 --> Undefined property: App\Controllers\WorkoutController::$db
#0 D:\xampp\htdocs\api\app\Controllers\WorkoutController.php(22): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined prope...', 'D:\\xampp\\htdocs...', 22, Array)
#1 D:\xampp\htdocs\api\system\CodeIgniter.php(824): App\Controllers\WorkoutController->putWorkout('12')
#2 D:\xampp\htdocs\api\system\CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\WorkoutController))
#3 D:\xampp\htdocs\api\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 D:\xampp\htdocs\api\index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2022-05-11 15:33:05 --> Undefined variable: model
#0 D:\xampp\htdocs\api\app\Controllers\WorkoutController.php(30): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined varia...', 'D:\\xampp\\htdocs...', 30, Array)
#1 D:\xampp\htdocs\api\system\CodeIgniter.php(824): App\Controllers\WorkoutController->putWorkout('12')
#2 D:\xampp\htdocs\api\system\CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\WorkoutController))
#3 D:\xampp\htdocs\api\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 D:\xampp\htdocs\api\index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2022-05-11 15:39:56 --> syntax error, unexpected ','
#0 D:\xampp\htdocs\api\system\Autoloader\Autoloader.php(241): CodeIgniter\Autoloader\Autoloader->includeFile('D:\\xampp\\htdocs...')
#1 D:\xampp\htdocs\api\system\Autoloader\Autoloader.php(219): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Controllers...')
#2 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Controllers...')
#3 [internal function]: spl_autoload_call('App\\Controllers...')
#4 D:\xampp\htdocs\api\system\CodeIgniter.php(789): class_exists('\\App\\Controller...', true)
#5 D:\xampp\htdocs\api\system\CodeIgniter.php(397): CodeIgniter\CodeIgniter->startController()
#6 D:\xampp\htdocs\api\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\xampp\htdocs\api\index.php(37): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2022-05-11 15:43:14 --> syntax error, unexpected '}', expecting ';'
#0 D:\xampp\htdocs\api\system\Autoloader\Autoloader.php(241): CodeIgniter\Autoloader\Autoloader->includeFile('D:\\xampp\\htdocs...')
#1 D:\xampp\htdocs\api\system\Autoloader\Autoloader.php(219): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Controllers...')
#2 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Controllers...')
#3 [internal function]: spl_autoload_call('App\\Controllers...')
#4 D:\xampp\htdocs\api\system\CodeIgniter.php(789): class_exists('\\App\\Controller...', true)
#5 D:\xampp\htdocs\api\system\CodeIgniter.php(397): CodeIgniter\CodeIgniter->startController()
#6 D:\xampp\htdocs\api\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\xampp\htdocs\api\index.php(37): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2022-05-11 15:44:18 --> syntax error, unexpected '}', expecting ';'
#0 D:\xampp\htdocs\api\system\Autoloader\Autoloader.php(241): CodeIgniter\Autoloader\Autoloader->includeFile('D:\\xampp\\htdocs...')
#1 D:\xampp\htdocs\api\system\Autoloader\Autoloader.php(219): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Controllers...')
#2 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Controllers...')
#3 [internal function]: spl_autoload_call('App\\Controllers...')
#4 D:\xampp\htdocs\api\system\CodeIgniter.php(789): class_exists('\\App\\Controller...', true)
#5 D:\xampp\htdocs\api\system\CodeIgniter.php(397): CodeIgniter\CodeIgniter->startController()
#6 D:\xampp\htdocs\api\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\xampp\htdocs\api\index.php(37): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2022-05-11 15:46:11 --> syntax error, unexpected '}', expecting ';'
#0 D:\xampp\htdocs\api\system\Autoloader\Autoloader.php(241): CodeIgniter\Autoloader\Autoloader->includeFile('D:\\xampp\\htdocs...')
#1 D:\xampp\htdocs\api\system\Autoloader\Autoloader.php(219): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Controllers...')
#2 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Controllers...')
#3 [internal function]: spl_autoload_call('App\\Controllers...')
#4 D:\xampp\htdocs\api\system\CodeIgniter.php(789): class_exists('\\App\\Controller...', true)
#5 D:\xampp\htdocs\api\system\CodeIgniter.php(397): CodeIgniter\CodeIgniter->startController()
#6 D:\xampp\htdocs\api\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\xampp\htdocs\api\index.php(37): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2022-05-11 16:32:29 --> Class 'App\Models\TodoModel' not found
#0 D:\xampp\htdocs\api\system\CodeIgniter.php(824): App\Controllers\TodoController->getTodo('12')
#1 D:\xampp\htdocs\api\system\CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TodoController))
#2 D:\xampp\htdocs\api\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 D:\xampp\htdocs\api\index.php(37): CodeIgniter\CodeIgniter->run()
#4 {main}
CRITICAL - 2022-05-11 16:33:08 --> Class 'App\Models\TodoModel' not found
#0 D:\xampp\htdocs\api\system\CodeIgniter.php(824): App\Controllers\TodoController->getTodo('12')
#1 D:\xampp\htdocs\api\system\CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TodoController))
#2 D:\xampp\htdocs\api\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 D:\xampp\htdocs\api\index.php(37): CodeIgniter\CodeIgniter->run()
#4 {main}
ERROR - 2022-05-11 16:36:31 --> Unknown column 'date' in 'where clause'
CRITICAL - 2022-05-11 16:36:31 --> Call to a member function getResult() on bool
#0 D:\xampp\htdocs\api\system\BaseModel.php(523): CodeIgniter\Model->doFind(false, NULL)
#1 D:\xampp\htdocs\api\app\Controllers\TodoController.php(55): CodeIgniter\BaseModel->find()
#2 D:\xampp\htdocs\api\system\CodeIgniter.php(824): App\Controllers\TodoController->getTodo('12')
#3 D:\xampp\htdocs\api\system\CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TodoController))
#4 D:\xampp\htdocs\api\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 D:\xampp\htdocs\api\index.php(37): CodeIgniter\CodeIgniter->run()
#6 {main}
CRITICAL - 2022-05-11 16:37:00 --> syntax error, unexpected 'Data' (T_STRING)
#0 D:\xampp\htdocs\api\system\Autoloader\Autoloader.php(241): CodeIgniter\Autoloader\Autoloader->includeFile('D:\\xampp\\htdocs...')
#1 D:\xampp\htdocs\api\system\Autoloader\Autoloader.php(219): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Controllers...')
#2 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Controllers...')
#3 [internal function]: spl_autoload_call('App\\Controllers...')
#4 D:\xampp\htdocs\api\system\CodeIgniter.php(789): class_exists('\\App\\Controller...', true)
#5 D:\xampp\htdocs\api\system\CodeIgniter.php(397): CodeIgniter\CodeIgniter->startController()
#6 D:\xampp\htdocs\api\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\xampp\htdocs\api\index.php(37): CodeIgniter\CodeIgniter->run()
#8 {main}
ERROR - 2022-05-11 16:37:08 --> Unknown column 'date' in 'where clause'
CRITICAL - 2022-05-11 16:37:08 --> Call to a member function getResult() on bool
#0 D:\xampp\htdocs\api\system\BaseModel.php(523): CodeIgniter\Model->doFind(false, NULL)
#1 D:\xampp\htdocs\api\app\Controllers\TodoController.php(56): CodeIgniter\BaseModel->find()
#2 D:\xampp\htdocs\api\system\CodeIgniter.php(824): App\Controllers\TodoController->getTodo('12')
#3 D:\xampp\htdocs\api\system\CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TodoController))
#4 D:\xampp\htdocs\api\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 D:\xampp\htdocs\api\index.php(37): CodeIgniter\CodeIgniter->run()
#6 {main}
CRITICAL - 2022-05-11 16:38:06 --> syntax error, unexpected '=', expecting ')'
#0 D:\xampp\htdocs\api\system\Autoloader\Autoloader.php(241): CodeIgniter\Autoloader\Autoloader->includeFile('D:\\xampp\\htdocs...')
#1 D:\xampp\htdocs\api\system\Autoloader\Autoloader.php(219): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Controllers...')
#2 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Controllers...')
#3 [internal function]: spl_autoload_call('App\\Controllers...')
#4 D:\xampp\htdocs\api\system\CodeIgniter.php(789): class_exists('\\App\\Controller...', true)
#5 D:\xampp\htdocs\api\system\CodeIgniter.php(397): CodeIgniter\CodeIgniter->startController()
#6 D:\xampp\htdocs\api\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\xampp\htdocs\api\index.php(37): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2022-05-11 16:38:43 --> syntax error, unexpected '$data' (T_VARIABLE)
#0 D:\xampp\htdocs\api\system\Autoloader\Autoloader.php(241): CodeIgniter\Autoloader\Autoloader->includeFile('D:\\xampp\\htdocs...')
#1 D:\xampp\htdocs\api\system\Autoloader\Autoloader.php(219): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Controllers...')
#2 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Controllers...')
#3 [internal function]: spl_autoload_call('App\\Controllers...')
#4 D:\xampp\htdocs\api\system\CodeIgniter.php(789): class_exists('\\App\\Controller...', true)
#5 D:\xampp\htdocs\api\system\CodeIgniter.php(397): CodeIgniter\CodeIgniter->startController()
#6 D:\xampp\htdocs\api\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\xampp\htdocs\api\index.php(37): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2022-05-11 16:39:54 --> syntax error, unexpected ','
#0 D:\xampp\htdocs\api\system\Autoloader\Autoloader.php(241): CodeIgniter\Autoloader\Autoloader->includeFile('D:\\xampp\\htdocs...')
#1 D:\xampp\htdocs\api\system\Autoloader\Autoloader.php(219): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Controllers...')
#2 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Controllers...')
#3 [internal function]: spl_autoload_call('App\\Controllers...')
#4 D:\xampp\htdocs\api\system\CodeIgniter.php(789): class_exists('\\App\\Controller...', true)
#5 D:\xampp\htdocs\api\system\CodeIgniter.php(397): CodeIgniter\CodeIgniter->startController()
#6 D:\xampp\htdocs\api\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\xampp\htdocs\api\index.php(37): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2022-05-11 16:41:18 --> syntax error, unexpected '=', expecting ')'
#0 D:\xampp\htdocs\api\system\Autoloader\Autoloader.php(241): CodeIgniter\Autoloader\Autoloader->includeFile('D:\\xampp\\htdocs...')
#1 D:\xampp\htdocs\api\system\Autoloader\Autoloader.php(219): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Controllers...')
#2 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Controllers...')
#3 [internal function]: spl_autoload_call('App\\Controllers...')
#4 D:\xampp\htdocs\api\system\CodeIgniter.php(789): class_exists('\\App\\Controller...', true)
#5 D:\xampp\htdocs\api\system\CodeIgniter.php(397): CodeIgniter\CodeIgniter->startController()
#6 D:\xampp\htdocs\api\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\xampp\htdocs\api\index.php(37): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2022-05-11 16:44:31 --> syntax error, unexpected '='
#0 D:\xampp\htdocs\api\system\Autoloader\Autoloader.php(241): CodeIgniter\Autoloader\Autoloader->includeFile('D:\\xampp\\htdocs...')
#1 D:\xampp\htdocs\api\system\Autoloader\Autoloader.php(219): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Controllers...')
#2 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Controllers...')
#3 [internal function]: spl_autoload_call('App\\Controllers...')
#4 D:\xampp\htdocs\api\system\CodeIgniter.php(789): class_exists('\\App\\Controller...', true)
#5 D:\xampp\htdocs\api\system\CodeIgniter.php(397): CodeIgniter\CodeIgniter->startController()
#6 D:\xampp\htdocs\api\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\xampp\htdocs\api\index.php(37): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2022-05-11 16:45:50 --> Call to undefined function App\Controllers\DESC()
#0 D:\xampp\htdocs\api\system\CodeIgniter.php(824): App\Controllers\TodoController->getTodo('12')
#1 D:\xampp\htdocs\api\system\CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TodoController))
#2 D:\xampp\htdocs\api\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 D:\xampp\htdocs\api\index.php(37): CodeIgniter\CodeIgniter->run()
#4 {main}
CRITICAL - 2022-05-11 16:59:33 --> syntax error, unexpected '=>' (T_DOUBLE_ARROW)
#0 D:\xampp\htdocs\api\system\Autoloader\Autoloader.php(241): CodeIgniter\Autoloader\Autoloader->includeFile('D:\\xampp\\htdocs...')
#1 D:\xampp\htdocs\api\system\Autoloader\Autoloader.php(219): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Controllers...')
#2 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Controllers...')
#3 [internal function]: spl_autoload_call('App\\Controllers...')
#4 D:\xampp\htdocs\api\system\CodeIgniter.php(789): class_exists('\\App\\Controller...', true)
#5 D:\xampp\htdocs\api\system\CodeIgniter.php(397): CodeIgniter\CodeIgniter->startController()
#6 D:\xampp\htdocs\api\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\xampp\htdocs\api\index.php(37): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2022-05-11 16:59:41 --> syntax error, unexpected '=>' (T_DOUBLE_ARROW)
#0 D:\xampp\htdocs\api\system\Autoloader\Autoloader.php(241): CodeIgniter\Autoloader\Autoloader->includeFile('D:\\xampp\\htdocs...')
#1 D:\xampp\htdocs\api\system\Autoloader\Autoloader.php(219): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Controllers...')
#2 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Controllers...')
#3 [internal function]: spl_autoload_call('App\\Controllers...')
#4 D:\xampp\htdocs\api\system\CodeIgniter.php(789): class_exists('\\App\\Controller...', true)
#5 D:\xampp\htdocs\api\system\CodeIgniter.php(397): CodeIgniter\CodeIgniter->startController()
#6 D:\xampp\htdocs\api\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\xampp\htdocs\api\index.php(37): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2022-05-11 17:01:27 --> syntax error, unexpected '=>' (T_DOUBLE_ARROW)
#0 D:\xampp\htdocs\api\system\Autoloader\Autoloader.php(241): CodeIgniter\Autoloader\Autoloader->includeFile('D:\\xampp\\htdocs...')
#1 D:\xampp\htdocs\api\system\Autoloader\Autoloader.php(219): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Controllers...')
#2 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Controllers...')
#3 [internal function]: spl_autoload_call('App\\Controllers...')
#4 D:\xampp\htdocs\api\system\CodeIgniter.php(789): class_exists('\\App\\Controller...', true)
#5 D:\xampp\htdocs\api\system\CodeIgniter.php(397): CodeIgniter\CodeIgniter->startController()
#6 D:\xampp\htdocs\api\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\xampp\htdocs\api\index.php(37): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2022-05-11 17:01:51 --> syntax error, unexpected '=>' (T_DOUBLE_ARROW)
#0 D:\xampp\htdocs\api\system\Autoloader\Autoloader.php(241): CodeIgniter\Autoloader\Autoloader->includeFile('D:\\xampp\\htdocs...')
#1 D:\xampp\htdocs\api\system\Autoloader\Autoloader.php(219): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Controllers...')
#2 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Controllers...')
#3 [internal function]: spl_autoload_call('App\\Controllers...')
#4 D:\xampp\htdocs\api\system\CodeIgniter.php(789): class_exists('\\App\\Controller...', true)
#5 D:\xampp\htdocs\api\system\CodeIgniter.php(397): CodeIgniter\CodeIgniter->startController()
#6 D:\xampp\htdocs\api\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\xampp\htdocs\api\index.php(37): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2022-05-11 17:01:54 --> syntax error, unexpected '=>' (T_DOUBLE_ARROW)
#0 D:\xampp\htdocs\api\system\Autoloader\Autoloader.php(241): CodeIgniter\Autoloader\Autoloader->includeFile('D:\\xampp\\htdocs...')
#1 D:\xampp\htdocs\api\system\Autoloader\Autoloader.php(219): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Controllers...')
#2 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Controllers...')
#3 [internal function]: spl_autoload_call('App\\Controllers...')
#4 D:\xampp\htdocs\api\system\CodeIgniter.php(789): class_exists('\\App\\Controller...', true)
#5 D:\xampp\htdocs\api\system\CodeIgniter.php(397): CodeIgniter\CodeIgniter->startController()
#6 D:\xampp\htdocs\api\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\xampp\htdocs\api\index.php(37): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2022-05-11 17:02:24 --> syntax error, unexpected '=>' (T_DOUBLE_ARROW)
#0 D:\xampp\htdocs\api\system\Autoloader\Autoloader.php(241): CodeIgniter\Autoloader\Autoloader->includeFile('D:\\xampp\\htdocs...')
#1 D:\xampp\htdocs\api\system\Autoloader\Autoloader.php(219): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Controllers...')
#2 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Controllers...')
#3 [internal function]: spl_autoload_call('App\\Controllers...')
#4 D:\xampp\htdocs\api\system\CodeIgniter.php(789): class_exists('\\App\\Controller...', true)
#5 D:\xampp\htdocs\api\system\CodeIgniter.php(397): CodeIgniter\CodeIgniter->startController()
#6 D:\xampp\htdocs\api\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\xampp\htdocs\api\index.php(37): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2022-05-11 17:03:23 --> syntax error, unexpected '=>' (T_DOUBLE_ARROW)
#0 D:\xampp\htdocs\api\system\Autoloader\Autoloader.php(241): CodeIgniter\Autoloader\Autoloader->includeFile('D:\\xampp\\htdocs...')
#1 D:\xampp\htdocs\api\system\Autoloader\Autoloader.php(219): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Controllers...')
#2 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Controllers...')
#3 [internal function]: spl_autoload_call('App\\Controllers...')
#4 D:\xampp\htdocs\api\system\CodeIgniter.php(789): class_exists('\\App\\Controller...', true)
#5 D:\xampp\htdocs\api\system\CodeIgniter.php(397): CodeIgniter\CodeIgniter->startController()
#6 D:\xampp\htdocs\api\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\xampp\htdocs\api\index.php(37): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2022-05-11 17:03:31 --> syntax error, unexpected '=>' (T_DOUBLE_ARROW)
#0 D:\xampp\htdocs\api\system\Autoloader\Autoloader.php(241): CodeIgniter\Autoloader\Autoloader->includeFile('D:\\xampp\\htdocs...')
#1 D:\xampp\htdocs\api\system\Autoloader\Autoloader.php(219): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Controllers...')
#2 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Controllers...')
#3 [internal function]: spl_autoload_call('App\\Controllers...')
#4 D:\xampp\htdocs\api\system\CodeIgniter.php(789): class_exists('\\App\\Controller...', true)
#5 D:\xampp\htdocs\api\system\CodeIgniter.php(397): CodeIgniter\CodeIgniter->startController()
#6 D:\xampp\htdocs\api\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\xampp\htdocs\api\index.php(37): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2022-05-11 17:03:57 --> syntax error, unexpected '=>' (T_DOUBLE_ARROW)
#0 D:\xampp\htdocs\api\system\Autoloader\Autoloader.php(241): CodeIgniter\Autoloader\Autoloader->includeFile('D:\\xampp\\htdocs...')
#1 D:\xampp\htdocs\api\system\Autoloader\Autoloader.php(219): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Controllers...')
#2 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Controllers...')
#3 [internal function]: spl_autoload_call('App\\Controllers...')
#4 D:\xampp\htdocs\api\system\CodeIgniter.php(789): class_exists('\\App\\Controller...', true)
#5 D:\xampp\htdocs\api\system\CodeIgniter.php(397): CodeIgniter\CodeIgniter->startController()
#6 D:\xampp\htdocs\api\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\xampp\htdocs\api\index.php(37): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2022-05-11 17:05:33 --> syntax error, unexpected '=>' (T_DOUBLE_ARROW)
#0 D:\xampp\htdocs\api\system\Autoloader\Autoloader.php(241): CodeIgniter\Autoloader\Autoloader->includeFile('D:\\xampp\\htdocs...')
#1 D:\xampp\htdocs\api\system\Autoloader\Autoloader.php(219): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Controllers...')
#2 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Controllers...')
#3 [internal function]: spl_autoload_call('App\\Controllers...')
#4 D:\xampp\htdocs\api\system\CodeIgniter.php(789): class_exists('\\App\\Controller...', true)
#5 D:\xampp\htdocs\api\system\CodeIgniter.php(397): CodeIgniter\CodeIgniter->startController()
#6 D:\xampp\htdocs\api\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\xampp\htdocs\api\index.php(37): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2022-05-11 17:07:40 --> syntax error, unexpected '=>' (T_DOUBLE_ARROW)
#0 D:\xampp\htdocs\api\system\Autoloader\Autoloader.php(241): CodeIgniter\Autoloader\Autoloader->includeFile('D:\\xampp\\htdocs...')
#1 D:\xampp\htdocs\api\system\Autoloader\Autoloader.php(219): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Controllers...')
#2 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Controllers...')
#3 [internal function]: spl_autoload_call('App\\Controllers...')
#4 D:\xampp\htdocs\api\system\CodeIgniter.php(789): class_exists('\\App\\Controller...', true)
#5 D:\xampp\htdocs\api\system\CodeIgniter.php(397): CodeIgniter\CodeIgniter->startController()
#6 D:\xampp\htdocs\api\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\xampp\htdocs\api\index.php(37): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2022-05-11 17:08:34 --> syntax error, unexpected '=>' (T_DOUBLE_ARROW)
#0 D:\xampp\htdocs\api\system\Autoloader\Autoloader.php(241): CodeIgniter\Autoloader\Autoloader->includeFile('D:\\xampp\\htdocs...')
#1 D:\xampp\htdocs\api\system\Autoloader\Autoloader.php(219): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Controllers...')
#2 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Controllers...')
#3 [internal function]: spl_autoload_call('App\\Controllers...')
#4 D:\xampp\htdocs\api\system\CodeIgniter.php(789): class_exists('\\App\\Controller...', true)
#5 D:\xampp\htdocs\api\system\CodeIgniter.php(397): CodeIgniter\CodeIgniter->startController()
#6 D:\xampp\htdocs\api\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\xampp\htdocs\api\index.php(37): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2022-05-11 17:10:45 --> syntax error, unexpected '=>' (T_DOUBLE_ARROW)
#0 D:\xampp\htdocs\api\system\Autoloader\Autoloader.php(241): CodeIgniter\Autoloader\Autoloader->includeFile('D:\\xampp\\htdocs...')
#1 D:\xampp\htdocs\api\system\Autoloader\Autoloader.php(219): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Controllers...')
#2 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Controllers...')
#3 [internal function]: spl_autoload_call('App\\Controllers...')
#4 D:\xampp\htdocs\api\system\CodeIgniter.php(789): class_exists('\\App\\Controller...', true)
#5 D:\xampp\htdocs\api\system\CodeIgniter.php(397): CodeIgniter\CodeIgniter->startController()
#6 D:\xampp\htdocs\api\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\xampp\htdocs\api\index.php(37): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2022-05-11 17:10:50 --> syntax error, unexpected '=>' (T_DOUBLE_ARROW)
#0 D:\xampp\htdocs\api\system\Autoloader\Autoloader.php(241): CodeIgniter\Autoloader\Autoloader->includeFile('D:\\xampp\\htdocs...')
#1 D:\xampp\htdocs\api\system\Autoloader\Autoloader.php(219): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Controllers...')
#2 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Controllers...')
#3 [internal function]: spl_autoload_call('App\\Controllers...')
#4 D:\xampp\htdocs\api\system\CodeIgniter.php(789): class_exists('\\App\\Controller...', true)
#5 D:\xampp\htdocs\api\system\CodeIgniter.php(397): CodeIgniter\CodeIgniter->startController()
#6 D:\xampp\htdocs\api\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\xampp\htdocs\api\index.php(37): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2022-05-11 17:11:28 --> syntax error, unexpected '=>' (T_DOUBLE_ARROW)
#0 D:\xampp\htdocs\api\system\Autoloader\Autoloader.php(241): CodeIgniter\Autoloader\Autoloader->includeFile('D:\\xampp\\htdocs...')
#1 D:\xampp\htdocs\api\system\Autoloader\Autoloader.php(219): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Controllers...')
#2 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Controllers...')
#3 [internal function]: spl_autoload_call('App\\Controllers...')
#4 D:\xampp\htdocs\api\system\CodeIgniter.php(789): class_exists('\\App\\Controller...', true)
#5 D:\xampp\htdocs\api\system\CodeIgniter.php(397): CodeIgniter\CodeIgniter->startController()
#6 D:\xampp\htdocs\api\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\xampp\htdocs\api\index.php(37): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2022-05-11 17:12:51 --> syntax error, unexpected '=>' (T_DOUBLE_ARROW)
#0 D:\xampp\htdocs\api\system\Autoloader\Autoloader.php(241): CodeIgniter\Autoloader\Autoloader->includeFile('D:\\xampp\\htdocs...')
#1 D:\xampp\htdocs\api\system\Autoloader\Autoloader.php(219): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Controllers...')
#2 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Controllers...')
#3 [internal function]: spl_autoload_call('App\\Controllers...')
#4 D:\xampp\htdocs\api\system\CodeIgniter.php(789): class_exists('\\App\\Controller...', true)
#5 D:\xampp\htdocs\api\system\CodeIgniter.php(397): CodeIgniter\CodeIgniter->startController()
#6 D:\xampp\htdocs\api\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\xampp\htdocs\api\index.php(37): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2022-05-11 17:12:55 --> syntax error, unexpected '=>' (T_DOUBLE_ARROW)
#0 D:\xampp\htdocs\api\system\Autoloader\Autoloader.php(241): CodeIgniter\Autoloader\Autoloader->includeFile('D:\\xampp\\htdocs...')
#1 D:\xampp\htdocs\api\system\Autoloader\Autoloader.php(219): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Controllers...')
#2 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Controllers...')
#3 [internal function]: spl_autoload_call('App\\Controllers...')
#4 D:\xampp\htdocs\api\system\CodeIgniter.php(789): class_exists('\\App\\Controller...', true)
#5 D:\xampp\htdocs\api\system\CodeIgniter.php(397): CodeIgniter\CodeIgniter->startController()
#6 D:\xampp\htdocs\api\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\xampp\htdocs\api\index.php(37): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2022-05-11 17:15:18 --> syntax error, unexpected '=>' (T_DOUBLE_ARROW)
#0 D:\xampp\htdocs\api\system\Autoloader\Autoloader.php(241): CodeIgniter\Autoloader\Autoloader->includeFile('D:\\xampp\\htdocs...')
#1 D:\xampp\htdocs\api\system\Autoloader\Autoloader.php(219): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Controllers...')
#2 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Controllers...')
#3 [internal function]: spl_autoload_call('App\\Controllers...')
#4 D:\xampp\htdocs\api\system\CodeIgniter.php(789): class_exists('\\App\\Controller...', true)
#5 D:\xampp\htdocs\api\system\CodeIgniter.php(397): CodeIgniter\CodeIgniter->startController()
#6 D:\xampp\htdocs\api\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\xampp\htdocs\api\index.php(37): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2022-05-11 17:36:10 --> There is no data to update.
#0 D:\xampp\htdocs\api\system\BaseModel.php(846): CodeIgniter\Database\Exceptions\DataException::forEmptyDataset('update')
#1 D:\xampp\htdocs\api\system\Model.php(646): CodeIgniter\BaseModel->update(Array, Array)
#2 D:\xampp\htdocs\api\app\Controllers\WorkoutController.php(29): CodeIgniter\Model->update('12', Array)
#3 D:\xampp\htdocs\api\system\CodeIgniter.php(824): App\Controllers\WorkoutController->putWorkout('12')
#4 D:\xampp\htdocs\api\system\CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\WorkoutController))
#5 D:\xampp\htdocs\api\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 D:\xampp\htdocs\api\index.php(37): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2022-05-11 17:43:12 --> There is no data to update.
#0 D:\xampp\htdocs\api\system\BaseModel.php(1574): CodeIgniter\Database\Exceptions\DataException::forEmptyDataset('update')
#1 D:\xampp\htdocs\api\system\BaseModel.php(832): CodeIgniter\BaseModel->transformDataToArray(NULL, 'update')
#2 D:\xampp\htdocs\api\system\Model.php(646): CodeIgniter\BaseModel->update(Array, NULL)
#3 D:\xampp\htdocs\api\app\Controllers\WorkoutController.php(29): CodeIgniter\Model->update(Array)
#4 D:\xampp\htdocs\api\system\CodeIgniter.php(824): App\Controllers\WorkoutController->putWorkout('12')
#5 D:\xampp\htdocs\api\system\CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\WorkoutController))
#6 D:\xampp\htdocs\api\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\xampp\htdocs\api\index.php(37): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2022-05-11 17:43:40 --> There is no data to update.
#0 D:\xampp\htdocs\api\system\BaseModel.php(1574): CodeIgniter\Database\Exceptions\DataException::forEmptyDataset('update')
#1 D:\xampp\htdocs\api\system\BaseModel.php(832): CodeIgniter\BaseModel->transformDataToArray(NULL, 'update')
#2 D:\xampp\htdocs\api\system\Model.php(646): CodeIgniter\BaseModel->update(Array, NULL)
#3 D:\xampp\htdocs\api\app\Controllers\WorkoutController.php(29): CodeIgniter\Model->update(Array)
#4 D:\xampp\htdocs\api\system\CodeIgniter.php(824): App\Controllers\WorkoutController->putWorkout('5')
#5 D:\xampp\htdocs\api\system\CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\WorkoutController))
#6 D:\xampp\htdocs\api\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\xampp\htdocs\api\index.php(37): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2022-05-11 17:44:49 --> There is no data to update.
#0 D:\xampp\htdocs\api\system\BaseModel.php(1574): CodeIgniter\Database\Exceptions\DataException::forEmptyDataset('update')
#1 D:\xampp\htdocs\api\system\BaseModel.php(832): CodeIgniter\BaseModel->transformDataToArray(NULL, 'update')
#2 D:\xampp\htdocs\api\system\Model.php(646): CodeIgniter\BaseModel->update(Array, NULL)
#3 D:\xampp\htdocs\api\app\Controllers\WorkoutController.php(29): CodeIgniter\Model->update(Array)
#4 D:\xampp\htdocs\api\system\CodeIgniter.php(824): App\Controllers\WorkoutController->putWorkout('5')
#5 D:\xampp\htdocs\api\system\CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\WorkoutController))
#6 D:\xampp\htdocs\api\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\xampp\htdocs\api\index.php(37): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2022-05-11 17:46:34 --> There is no data to update.
#0 D:\xampp\htdocs\api\system\BaseModel.php(1574): CodeIgniter\Database\Exceptions\DataException::forEmptyDataset('update')
#1 D:\xampp\htdocs\api\system\BaseModel.php(832): CodeIgniter\BaseModel->transformDataToArray(NULL, 'update')
#2 D:\xampp\htdocs\api\system\Model.php(646): CodeIgniter\BaseModel->update(Array, NULL)
#3 D:\xampp\htdocs\api\app\Controllers\WorkoutController.php(29): CodeIgniter\Model->update(Array)
#4 D:\xampp\htdocs\api\system\CodeIgniter.php(824): App\Controllers\WorkoutController->putWorkout('8')
#5 D:\xampp\htdocs\api\system\CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\WorkoutController))
#6 D:\xampp\htdocs\api\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\xampp\htdocs\api\index.php(37): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2022-05-11 17:46:48 --> There is no data to update.
#0 D:\xampp\htdocs\api\system\BaseModel.php(1574): CodeIgniter\Database\Exceptions\DataException::forEmptyDataset('update')
#1 D:\xampp\htdocs\api\system\BaseModel.php(832): CodeIgniter\BaseModel->transformDataToArray(NULL, 'update')
#2 D:\xampp\htdocs\api\system\Model.php(646): CodeIgniter\BaseModel->update(Array, NULL)
#3 D:\xampp\htdocs\api\app\Controllers\WorkoutController.php(29): CodeIgniter\Model->update(Array)
#4 D:\xampp\htdocs\api\system\CodeIgniter.php(824): App\Controllers\WorkoutController->putWorkout('8')
#5 D:\xampp\htdocs\api\system\CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\WorkoutController))
#6 D:\xampp\htdocs\api\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\xampp\htdocs\api\index.php(37): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2022-05-11 17:46:59 --> There is no data to update.
#0 D:\xampp\htdocs\api\system\BaseModel.php(1574): CodeIgniter\Database\Exceptions\DataException::forEmptyDataset('update')
#1 D:\xampp\htdocs\api\system\BaseModel.php(832): CodeIgniter\BaseModel->transformDataToArray(NULL, 'update')
#2 D:\xampp\htdocs\api\system\Model.php(646): CodeIgniter\BaseModel->update(Array, NULL)
#3 D:\xampp\htdocs\api\app\Controllers\WorkoutController.php(29): CodeIgniter\Model->update(Array)
#4 D:\xampp\htdocs\api\system\CodeIgniter.php(824): App\Controllers\WorkoutController->putWorkout('8')
#5 D:\xampp\htdocs\api\system\CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\WorkoutController))
#6 D:\xampp\htdocs\api\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\xampp\htdocs\api\index.php(37): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2022-05-11 17:48:49 --> There is no data to update.
#0 D:\xampp\htdocs\api\system\BaseModel.php(1574): CodeIgniter\Database\Exceptions\DataException::forEmptyDataset('update')
#1 D:\xampp\htdocs\api\system\BaseModel.php(832): CodeIgniter\BaseModel->transformDataToArray(NULL, 'update')
#2 D:\xampp\htdocs\api\system\Model.php(646): CodeIgniter\BaseModel->update(Array, NULL)
#3 D:\xampp\htdocs\api\app\Controllers\WorkoutController.php(29): CodeIgniter\Model->update(Array)
#4 D:\xampp\htdocs\api\system\CodeIgniter.php(824): App\Controllers\WorkoutController->putWorkout('12')
#5 D:\xampp\htdocs\api\system\CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\WorkoutController))
#6 D:\xampp\htdocs\api\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\xampp\htdocs\api\index.php(37): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2022-05-11 17:52:59 --> There is no data to update.
#0 D:\xampp\htdocs\api\system\BaseModel.php(1574): CodeIgniter\Database\Exceptions\DataException::forEmptyDataset('update')
#1 D:\xampp\htdocs\api\system\BaseModel.php(832): CodeIgniter\BaseModel->transformDataToArray(NULL, 'update')
#2 D:\xampp\htdocs\api\system\Model.php(646): CodeIgniter\BaseModel->update(Array, NULL)
#3 D:\xampp\htdocs\api\app\Controllers\WorkoutController.php(29): CodeIgniter\Model->update(Array)
#4 D:\xampp\htdocs\api\system\CodeIgniter.php(824): App\Controllers\WorkoutController->putWorkout('12')
#5 D:\xampp\htdocs\api\system\CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\WorkoutController))
#6 D:\xampp\htdocs\api\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\xampp\htdocs\api\index.php(37): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2022-05-11 17:53:12 --> There is no data to update.
#0 D:\xampp\htdocs\api\system\BaseModel.php(1574): CodeIgniter\Database\Exceptions\DataException::forEmptyDataset('update')
#1 D:\xampp\htdocs\api\system\BaseModel.php(832): CodeIgniter\BaseModel->transformDataToArray(NULL, 'update')
#2 D:\xampp\htdocs\api\system\Model.php(646): CodeIgniter\BaseModel->update(Array, NULL)
#3 D:\xampp\htdocs\api\app\Controllers\WorkoutController.php(29): CodeIgniter\Model->update(Array)
#4 D:\xampp\htdocs\api\system\CodeIgniter.php(824): App\Controllers\WorkoutController->putWorkout('12')
#5 D:\xampp\htdocs\api\system\CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\WorkoutController))
#6 D:\xampp\htdocs\api\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\xampp\htdocs\api\index.php(37): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2022-05-11 18:03:04 --> syntax error, unexpected '(', expecting identifier (T_STRING) or variable (T_VARIABLE) or '{' or '$'
#0 D:\xampp\htdocs\api\system\Autoloader\Autoloader.php(241): CodeIgniter\Autoloader\Autoloader->includeFile('D:\\xampp\\htdocs...')
#1 D:\xampp\htdocs\api\system\Autoloader\Autoloader.php(219): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Controllers...')
#2 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Controllers...')
#3 [internal function]: spl_autoload_call('App\\Controllers...')
#4 D:\xampp\htdocs\api\system\CodeIgniter.php(789): class_exists('\\App\\Controller...', true)
#5 D:\xampp\htdocs\api\system\CodeIgniter.php(397): CodeIgniter\CodeIgniter->startController()
#6 D:\xampp\htdocs\api\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\xampp\htdocs\api\index.php(37): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2022-05-11 18:05:31 --> syntax error, unexpected '=>' (T_DOUBLE_ARROW)
#0 D:\xampp\htdocs\api\system\Autoloader\Autoloader.php(241): CodeIgniter\Autoloader\Autoloader->includeFile('D:\\xampp\\htdocs...')
#1 D:\xampp\htdocs\api\system\Autoloader\Autoloader.php(219): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Controllers...')
#2 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Controllers...')
#3 [internal function]: spl_autoload_call('App\\Controllers...')
#4 D:\xampp\htdocs\api\system\CodeIgniter.php(789): class_exists('\\App\\Controller...', true)
#5 D:\xampp\htdocs\api\system\CodeIgniter.php(397): CodeIgniter\CodeIgniter->startController()
#6 D:\xampp\htdocs\api\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\xampp\htdocs\api\index.php(37): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2022-05-11 18:09:10 --> syntax error, unexpected '=>' (T_DOUBLE_ARROW)
#0 D:\xampp\htdocs\api\system\Autoloader\Autoloader.php(241): CodeIgniter\Autoloader\Autoloader->includeFile('D:\\xampp\\htdocs...')
#1 D:\xampp\htdocs\api\system\Autoloader\Autoloader.php(219): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Controllers...')
#2 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Controllers...')
#3 [internal function]: spl_autoload_call('App\\Controllers...')
#4 D:\xampp\htdocs\api\system\CodeIgniter.php(789): class_exists('\\App\\Controller...', true)
#5 D:\xampp\htdocs\api\system\CodeIgniter.php(397): CodeIgniter\CodeIgniter->startController()
#6 D:\xampp\htdocs\api\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\xampp\htdocs\api\index.php(37): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2022-05-11 18:09:51 --> syntax error, unexpected '=>' (T_DOUBLE_ARROW)
#0 D:\xampp\htdocs\api\system\Autoloader\Autoloader.php(241): CodeIgniter\Autoloader\Autoloader->includeFile('D:\\xampp\\htdocs...')
#1 D:\xampp\htdocs\api\system\Autoloader\Autoloader.php(219): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Controllers...')
#2 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Controllers...')
#3 [internal function]: spl_autoload_call('App\\Controllers...')
#4 D:\xampp\htdocs\api\system\CodeIgniter.php(789): class_exists('\\App\\Controller...', true)
#5 D:\xampp\htdocs\api\system\CodeIgniter.php(397): CodeIgniter\CodeIgniter->startController()
#6 D:\xampp\htdocs\api\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\xampp\htdocs\api\index.php(37): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2022-05-11 18:11:36 --> syntax error, unexpected '=>' (T_DOUBLE_ARROW)
#0 D:\xampp\htdocs\api\system\Autoloader\Autoloader.php(241): CodeIgniter\Autoloader\Autoloader->includeFile('D:\\xampp\\htdocs...')
#1 D:\xampp\htdocs\api\system\Autoloader\Autoloader.php(219): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Controllers...')
#2 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Controllers...')
#3 [internal function]: spl_autoload_call('App\\Controllers...')
#4 D:\xampp\htdocs\api\system\CodeIgniter.php(789): class_exists('\\App\\Controller...', true)
#5 D:\xampp\htdocs\api\system\CodeIgniter.php(397): CodeIgniter\CodeIgniter->startController()
#6 D:\xampp\htdocs\api\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\xampp\htdocs\api\index.php(37): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2022-05-11 18:11:40 --> syntax error, unexpected '=>' (T_DOUBLE_ARROW)
#0 D:\xampp\htdocs\api\system\Autoloader\Autoloader.php(241): CodeIgniter\Autoloader\Autoloader->includeFile('D:\\xampp\\htdocs...')
#1 D:\xampp\htdocs\api\system\Autoloader\Autoloader.php(219): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Controllers...')
#2 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Controllers...')
#3 [internal function]: spl_autoload_call('App\\Controllers...')
#4 D:\xampp\htdocs\api\system\CodeIgniter.php(789): class_exists('\\App\\Controller...', true)
#5 D:\xampp\htdocs\api\system\CodeIgniter.php(397): CodeIgniter\CodeIgniter->startController()
#6 D:\xampp\htdocs\api\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\xampp\htdocs\api\index.php(37): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2022-05-11 18:11:44 --> syntax error, unexpected '=>' (T_DOUBLE_ARROW)
#0 D:\xampp\htdocs\api\system\Autoloader\Autoloader.php(241): CodeIgniter\Autoloader\Autoloader->includeFile('D:\\xampp\\htdocs...')
#1 D:\xampp\htdocs\api\system\Autoloader\Autoloader.php(219): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Controllers...')
#2 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Controllers...')
#3 [internal function]: spl_autoload_call('App\\Controllers...')
#4 D:\xampp\htdocs\api\system\CodeIgniter.php(789): class_exists('\\App\\Controller...', true)
#5 D:\xampp\htdocs\api\system\CodeIgniter.php(397): CodeIgniter\CodeIgniter->startController()
#6 D:\xampp\htdocs\api\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\xampp\htdocs\api\index.php(37): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2022-05-11 18:14:04 --> syntax error, unexpected '=>' (T_DOUBLE_ARROW)
#0 D:\xampp\htdocs\api\system\Autoloader\Autoloader.php(241): CodeIgniter\Autoloader\Autoloader->includeFile('D:\\xampp\\htdocs...')
#1 D:\xampp\htdocs\api\system\Autoloader\Autoloader.php(219): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Controllers...')
#2 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Controllers...')
#3 [internal function]: spl_autoload_call('App\\Controllers...')
#4 D:\xampp\htdocs\api\system\CodeIgniter.php(789): class_exists('\\App\\Controller...', true)
#5 D:\xampp\htdocs\api\system\CodeIgniter.php(397): CodeIgniter\CodeIgniter->startController()
#6 D:\xampp\htdocs\api\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\xampp\htdocs\api\index.php(37): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2022-05-11 18:14:07 --> syntax error, unexpected '=>' (T_DOUBLE_ARROW)
#0 D:\xampp\htdocs\api\system\Autoloader\Autoloader.php(241): CodeIgniter\Autoloader\Autoloader->includeFile('D:\\xampp\\htdocs...')
#1 D:\xampp\htdocs\api\system\Autoloader\Autoloader.php(219): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Controllers...')
#2 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Controllers...')
#3 [internal function]: spl_autoload_call('App\\Controllers...')
#4 D:\xampp\htdocs\api\system\CodeIgniter.php(789): class_exists('\\App\\Controller...', true)
#5 D:\xampp\htdocs\api\system\CodeIgniter.php(397): CodeIgniter\CodeIgniter->startController()
#6 D:\xampp\htdocs\api\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\xampp\htdocs\api\index.php(37): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2022-05-11 18:14:33 --> syntax error, unexpected '=>' (T_DOUBLE_ARROW)
#0 D:\xampp\htdocs\api\system\Autoloader\Autoloader.php(241): CodeIgniter\Autoloader\Autoloader->includeFile('D:\\xampp\\htdocs...')
#1 D:\xampp\htdocs\api\system\Autoloader\Autoloader.php(219): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Controllers...')
#2 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Controllers...')
#3 [internal function]: spl_autoload_call('App\\Controllers...')
#4 D:\xampp\htdocs\api\system\CodeIgniter.php(789): class_exists('\\App\\Controller...', true)
#5 D:\xampp\htdocs\api\system\CodeIgniter.php(397): CodeIgniter\CodeIgniter->startController()
#6 D:\xampp\htdocs\api\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\xampp\htdocs\api\index.php(37): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2022-05-11 18:14:38 --> syntax error, unexpected '=>' (T_DOUBLE_ARROW)
#0 D:\xampp\htdocs\api\system\Autoloader\Autoloader.php(241): CodeIgniter\Autoloader\Autoloader->includeFile('D:\\xampp\\htdocs...')
#1 D:\xampp\htdocs\api\system\Autoloader\Autoloader.php(219): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Controllers...')
#2 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Controllers...')
#3 [internal function]: spl_autoload_call('App\\Controllers...')
#4 D:\xampp\htdocs\api\system\CodeIgniter.php(789): class_exists('\\App\\Controller...', true)
#5 D:\xampp\htdocs\api\system\CodeIgniter.php(397): CodeIgniter\CodeIgniter->startController()
#6 D:\xampp\htdocs\api\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\xampp\htdocs\api\index.php(37): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2022-05-11 18:15:26 --> syntax error, unexpected '=>' (T_DOUBLE_ARROW)
#0 D:\xampp\htdocs\api\system\Autoloader\Autoloader.php(241): CodeIgniter\Autoloader\Autoloader->includeFile('D:\\xampp\\htdocs...')
#1 D:\xampp\htdocs\api\system\Autoloader\Autoloader.php(219): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Controllers...')
#2 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Controllers...')
#3 [internal function]: spl_autoload_call('App\\Controllers...')
#4 D:\xampp\htdocs\api\system\CodeIgniter.php(789): class_exists('\\App\\Controller...', true)
#5 D:\xampp\htdocs\api\system\CodeIgniter.php(397): CodeIgniter\CodeIgniter->startController()
#6 D:\xampp\htdocs\api\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\xampp\htdocs\api\index.php(37): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2022-05-11 18:15:30 --> syntax error, unexpected '=>' (T_DOUBLE_ARROW)
#0 D:\xampp\htdocs\api\system\Autoloader\Autoloader.php(241): CodeIgniter\Autoloader\Autoloader->includeFile('D:\\xampp\\htdocs...')
#1 D:\xampp\htdocs\api\system\Autoloader\Autoloader.php(219): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Controllers...')
#2 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Controllers...')
#3 [internal function]: spl_autoload_call('App\\Controllers...')
#4 D:\xampp\htdocs\api\system\CodeIgniter.php(789): class_exists('\\App\\Controller...', true)
#5 D:\xampp\htdocs\api\system\CodeIgniter.php(397): CodeIgniter\CodeIgniter->startController()
#6 D:\xampp\htdocs\api\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\xampp\htdocs\api\index.php(37): CodeIgniter\CodeIgniter->run()
#8 {main}
