CRITICAL - 2022-05-09 07:33:01 --> The framework needs the following extension(s) installed and loaded: intl.
#0 D:\xampp\htdocs\api\system\CodeIgniter.php(219): CodeIgniter\Exceptions\FrameworkException::forMissingExtension('intl')
#1 D:\xampp\htdocs\api\system\CodeIgniter.php(177): CodeIgniter\CodeIgniter->resolvePlatformExtensions()
#2 D:\xampp\htdocs\api\system\bootstrap.php(146): CodeIgniter\CodeIgniter->initialize()
#3 D:\xampp\htdocs\api\index.php(28): require('D:\\xampp\\htdocs...')
#4 {main}
CRITICAL - 2022-05-09 07:34:31 --> The framework needs the following extension(s) installed and loaded: intl.
#0 D:\xampp\htdocs\api\system\CodeIgniter.php(219): CodeIgniter\Exceptions\FrameworkException::forMissingExtension('intl')
#1 D:\xampp\htdocs\api\system\CodeIgniter.php(177): CodeIgniter\CodeIgniter->resolvePlatformExtensions()
#2 D:\xampp\htdocs\api\system\bootstrap.php(146): CodeIgniter\CodeIgniter->initialize()
#3 D:\xampp\htdocs\api\index.php(28): require('D:\\xampp\\htdocs...')
#4 {main}
CRITICAL - 2022-05-09 07:34:34 --> The framework needs the following extension(s) installed and loaded: intl.
#0 D:\xampp\htdocs\api\system\CodeIgniter.php(219): CodeIgniter\Exceptions\FrameworkException::forMissingExtension('intl')
#1 D:\xampp\htdocs\api\system\CodeIgniter.php(177): CodeIgniter\CodeIgniter->resolvePlatformExtensions()
#2 D:\xampp\htdocs\api\system\bootstrap.php(146): CodeIgniter\CodeIgniter->initialize()
#3 D:\xampp\htdocs\api\index.php(28): require('D:\\xampp\\htdocs...')
#4 {main}
CRITICAL - 2022-05-09 05:36:24 --> The framework needs the following extension(s) installed and loaded: curl, intl, mbstring.
#0 D:\xampp\htdocs\api\system\CodeIgniter.php(219): CodeIgniter\Exceptions\FrameworkException::forMissingExtension('curl, intl, mbs...')
#1 D:\xampp\htdocs\api\system\CodeIgniter.php(177): CodeIgniter\CodeIgniter->resolvePlatformExtensions()
#2 D:\xampp\htdocs\api\system\bootstrap.php(146): CodeIgniter\CodeIgniter->initialize()
#3 D:\xampp\htdocs\api\index.php(28): require('D:\\xampp\\htdocs...')
#4 {main}
CRITICAL - 2022-05-09 05:36:28 --> The framework needs the following extension(s) installed and loaded: curl, intl, mbstring.
#0 D:\xampp\htdocs\api\system\CodeIgniter.php(219): CodeIgniter\Exceptions\FrameworkException::forMissingExtension('curl, intl, mbs...')
#1 D:\xampp\htdocs\api\system\CodeIgniter.php(177): CodeIgniter\CodeIgniter->resolvePlatformExtensions()
#2 D:\xampp\htdocs\api\system\bootstrap.php(146): CodeIgniter\CodeIgniter->initialize()
#3 D:\xampp\htdocs\api\index.php(28): require('D:\\xampp\\htdocs...')
#4 {main}
CRITICAL - 2022-05-09 05:36:30 --> The framework needs the following extension(s) installed and loaded: curl, intl, mbstring.
#0 D:\xampp\htdocs\api\system\CodeIgniter.php(219): CodeIgniter\Exceptions\FrameworkException::forMissingExtension('curl, intl, mbs...')
#1 D:\xampp\htdocs\api\system\CodeIgniter.php(177): CodeIgniter\CodeIgniter->resolvePlatformExtensions()
#2 D:\xampp\htdocs\api\system\bootstrap.php(146): CodeIgniter\CodeIgniter->initialize()
#3 D:\xampp\htdocs\api\index.php(28): require('D:\\xampp\\htdocs...')
#4 {main}
CRITICAL - 2022-05-09 05:40:03 --> The framework needs the following extension(s) installed and loaded: curl, intl, mbstring.
#0 D:\xampp\htdocs\api\system\CodeIgniter.php(219): CodeIgniter\Exceptions\FrameworkException::forMissingExtension('curl, intl, mbs...')
#1 D:\xampp\htdocs\api\system\CodeIgniter.php(177): CodeIgniter\CodeIgniter->resolvePlatformExtensions()
#2 D:\xampp\htdocs\api\system\bootstrap.php(146): CodeIgniter\CodeIgniter->initialize()
#3 D:\xampp\htdocs\api\index.php(28): require('D:\\xampp\\htdocs...')
#4 {main}
CRITICAL - 2022-05-09 11:18:15 --> syntax error, unexpected '*', expecting end of file
#0 D:\xampp\htdocs\api\system\CodeIgniter.php(359): CodeIgniter\CodeIgniter->tryToRouteIt(NULL)
#1 D:\xampp\htdocs\api\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#2 D:\xampp\htdocs\api\index.php(37): CodeIgniter\CodeIgniter->run()
#3 {main}
CRITICAL - 2022-05-09 11:37:43 --> syntax error, unexpected ';', expecting ']'
#0 D:\xampp\htdocs\api\system\Autoloader\Autoloader.php(241): CodeIgniter\Autoloader\Autoloader->includeFile('D:\\xampp\\htdocs...')
#1 D:\xampp\htdocs\api\system\Autoloader\Autoloader.php(219): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Controllers...')
#2 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Controllers...')
#3 [internal function]: spl_autoload_call('App\\Controllers...')
#4 D:\xampp\htdocs\api\system\CodeIgniter.php(789): class_exists('\\App\\Controller...', true)
#5 D:\xampp\htdocs\api\system\CodeIgniter.php(397): CodeIgniter\CodeIgniter->startController()
#6 D:\xampp\htdocs\api\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\xampp\htdocs\api\index.php(37): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2022-05-09 11:38:01 --> syntax error, unexpected ';', expecting ']'
#0 D:\xampp\htdocs\api\system\Autoloader\Autoloader.php(241): CodeIgniter\Autoloader\Autoloader->includeFile('D:\\xampp\\htdocs...')
#1 D:\xampp\htdocs\api\system\Autoloader\Autoloader.php(219): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Controllers...')
#2 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Controllers...')
#3 [internal function]: spl_autoload_call('App\\Controllers...')
#4 D:\xampp\htdocs\api\system\CodeIgniter.php(789): class_exists('\\App\\Controller...', true)
#5 D:\xampp\htdocs\api\system\CodeIgniter.php(397): CodeIgniter\CodeIgniter->startController()
#6 D:\xampp\htdocs\api\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\xampp\htdocs\api\index.php(37): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2022-05-09 11:38:03 --> syntax error, unexpected ';', expecting ']'
#0 D:\xampp\htdocs\api\system\Autoloader\Autoloader.php(241): CodeIgniter\Autoloader\Autoloader->includeFile('D:\\xampp\\htdocs...')
#1 D:\xampp\htdocs\api\system\Autoloader\Autoloader.php(219): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Controllers...')
#2 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Controllers...')
#3 [internal function]: spl_autoload_call('App\\Controllers...')
#4 D:\xampp\htdocs\api\system\CodeIgniter.php(789): class_exists('\\App\\Controller...', true)
#5 D:\xampp\htdocs\api\system\CodeIgniter.php(397): CodeIgniter\CodeIgniter->startController()
#6 D:\xampp\htdocs\api\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\xampp\htdocs\api\index.php(37): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2022-05-09 11:38:03 --> syntax error, unexpected ';', expecting ']'
#0 D:\xampp\htdocs\api\system\Autoloader\Autoloader.php(241): CodeIgniter\Autoloader\Autoloader->includeFile('D:\\xampp\\htdocs...')
#1 D:\xampp\htdocs\api\system\Autoloader\Autoloader.php(219): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Controllers...')
#2 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Controllers...')
#3 [internal function]: spl_autoload_call('App\\Controllers...')
#4 D:\xampp\htdocs\api\system\CodeIgniter.php(789): class_exists('\\App\\Controller...', true)
#5 D:\xampp\htdocs\api\system\CodeIgniter.php(397): CodeIgniter\CodeIgniter->startController()
#6 D:\xampp\htdocs\api\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\xampp\htdocs\api\index.php(37): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2022-05-09 11:38:17 --> syntax error, unexpected ';', expecting ']'
#0 D:\xampp\htdocs\api\system\Autoloader\Autoloader.php(241): CodeIgniter\Autoloader\Autoloader->includeFile('D:\\xampp\\htdocs...')
#1 D:\xampp\htdocs\api\system\Autoloader\Autoloader.php(219): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Controllers...')
#2 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Controllers...')
#3 [internal function]: spl_autoload_call('App\\Controllers...')
#4 D:\xampp\htdocs\api\system\CodeIgniter.php(789): class_exists('\\App\\Controller...', true)
#5 D:\xampp\htdocs\api\system\CodeIgniter.php(397): CodeIgniter\CodeIgniter->startController()
#6 D:\xampp\htdocs\api\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\xampp\htdocs\api\index.php(37): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2022-05-09 11:38:18 --> syntax error, unexpected ';', expecting ']'
#0 D:\xampp\htdocs\api\system\Autoloader\Autoloader.php(241): CodeIgniter\Autoloader\Autoloader->includeFile('D:\\xampp\\htdocs...')
#1 D:\xampp\htdocs\api\system\Autoloader\Autoloader.php(219): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Controllers...')
#2 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Controllers...')
#3 [internal function]: spl_autoload_call('App\\Controllers...')
#4 D:\xampp\htdocs\api\system\CodeIgniter.php(789): class_exists('\\App\\Controller...', true)
#5 D:\xampp\htdocs\api\system\CodeIgniter.php(397): CodeIgniter\CodeIgniter->startController()
#6 D:\xampp\htdocs\api\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\xampp\htdocs\api\index.php(37): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2022-05-09 11:38:43 --> syntax error, unexpected 'public' (T_PUBLIC), expecting end of file
#0 D:\xampp\htdocs\api\system\Autoloader\Autoloader.php(241): CodeIgniter\Autoloader\Autoloader->includeFile('D:\\xampp\\htdocs...')
#1 D:\xampp\htdocs\api\system\Autoloader\Autoloader.php(219): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Controllers...')
#2 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Controllers...')
#3 [internal function]: spl_autoload_call('App\\Controllers...')
#4 D:\xampp\htdocs\api\system\CodeIgniter.php(789): class_exists('\\App\\Controller...', true)
#5 D:\xampp\htdocs\api\system\CodeIgniter.php(397): CodeIgniter\CodeIgniter->startController()
#6 D:\xampp\htdocs\api\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\xampp\htdocs\api\index.php(37): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2022-05-09 11:38:44 --> syntax error, unexpected 'public' (T_PUBLIC), expecting end of file
#0 D:\xampp\htdocs\api\system\Autoloader\Autoloader.php(241): CodeIgniter\Autoloader\Autoloader->includeFile('D:\\xampp\\htdocs...')
#1 D:\xampp\htdocs\api\system\Autoloader\Autoloader.php(219): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Controllers...')
#2 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Controllers...')
#3 [internal function]: spl_autoload_call('App\\Controllers...')
#4 D:\xampp\htdocs\api\system\CodeIgniter.php(789): class_exists('\\App\\Controller...', true)
#5 D:\xampp\htdocs\api\system\CodeIgniter.php(397): CodeIgniter\CodeIgniter->startController()
#6 D:\xampp\htdocs\api\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\xampp\htdocs\api\index.php(37): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2022-05-09 11:48:31 --> There is no data to insert.
#0 D:\xampp\htdocs\api\system\BaseModel.php(718): CodeIgniter\Database\Exceptions\DataException::forEmptyDataset('insert')
#1 D:\xampp\htdocs\api\system\Model.php(620): CodeIgniter\BaseModel->insert(Array, true)
#2 D:\xampp\htdocs\api\app\Controllers\UserController.php(76): CodeIgniter\Model->insert(Array)
#3 D:\xampp\htdocs\api\system\CodeIgniter.php(824): App\Controllers\UserController->insertdata()
#4 D:\xampp\htdocs\api\system\CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UserController))
#5 D:\xampp\htdocs\api\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 D:\xampp\htdocs\api\index.php(37): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2022-05-09 11:48:37 --> There is no data to insert.
#0 D:\xampp\htdocs\api\system\BaseModel.php(718): CodeIgniter\Database\Exceptions\DataException::forEmptyDataset('insert')
#1 D:\xampp\htdocs\api\system\Model.php(620): CodeIgniter\BaseModel->insert(Array, true)
#2 D:\xampp\htdocs\api\app\Controllers\UserController.php(76): CodeIgniter\Model->insert(Array)
#3 D:\xampp\htdocs\api\system\CodeIgniter.php(824): App\Controllers\UserController->insertdata()
#4 D:\xampp\htdocs\api\system\CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UserController))
#5 D:\xampp\htdocs\api\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 D:\xampp\htdocs\api\index.php(37): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2022-05-09 11:49:35 --> There is no data to insert.
#0 D:\xampp\htdocs\api\system\BaseModel.php(718): CodeIgniter\Database\Exceptions\DataException::forEmptyDataset('insert')
#1 D:\xampp\htdocs\api\system\Model.php(620): CodeIgniter\BaseModel->insert(Array, true)
#2 D:\xampp\htdocs\api\app\Controllers\UserController.php(76): CodeIgniter\Model->insert(Array)
#3 D:\xampp\htdocs\api\system\CodeIgniter.php(824): App\Controllers\UserController->insertdata()
#4 D:\xampp\htdocs\api\system\CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UserController))
#5 D:\xampp\htdocs\api\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 D:\xampp\htdocs\api\index.php(37): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2022-05-09 11:50:16 --> There is no data to insert.
#0 D:\xampp\htdocs\api\system\BaseModel.php(718): CodeIgniter\Database\Exceptions\DataException::forEmptyDataset('insert')
#1 D:\xampp\htdocs\api\system\Model.php(620): CodeIgniter\BaseModel->insert(Array, true)
#2 D:\xampp\htdocs\api\app\Controllers\UserController.php(76): CodeIgniter\Model->insert(Array)
#3 D:\xampp\htdocs\api\system\CodeIgniter.php(824): App\Controllers\UserController->insertdata()
#4 D:\xampp\htdocs\api\system\CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UserController))
#5 D:\xampp\htdocs\api\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 D:\xampp\htdocs\api\index.php(37): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2022-05-09 11:50:59 --> Argument 2 passed to dot_array_search() must be of the type array, null given, called in D:\xampp\htdocs\api\system\HTTP\IncomingRequest.php on line 538
#0 D:\xampp\htdocs\api\system\HTTP\IncomingRequest.php(538): dot_array_search('users_name', NULL)
#1 D:\xampp\htdocs\api\system\HTTP\IncomingRequest.php(498): CodeIgniter\HTTP\IncomingRequest->getJsonVar('users_name', false, NULL, NULL)
#2 D:\xampp\htdocs\api\app\Controllers\UserController.php(70): CodeIgniter\HTTP\IncomingRequest->getVar('users_name')
#3 D:\xampp\htdocs\api\system\CodeIgniter.php(824): App\Controllers\UserController->insertdata()
#4 D:\xampp\htdocs\api\system\CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UserController))
#5 D:\xampp\htdocs\api\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 D:\xampp\htdocs\api\index.php(37): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2022-05-09 11:51:35 --> There is no data to insert.
#0 D:\xampp\htdocs\api\system\BaseModel.php(718): CodeIgniter\Database\Exceptions\DataException::forEmptyDataset('insert')
#1 D:\xampp\htdocs\api\system\Model.php(620): CodeIgniter\BaseModel->insert(Array, true)
#2 D:\xampp\htdocs\api\app\Controllers\UserController.php(76): CodeIgniter\Model->insert(Array)
#3 D:\xampp\htdocs\api\system\CodeIgniter.php(824): App\Controllers\UserController->insertdata()
#4 D:\xampp\htdocs\api\system\CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UserController))
#5 D:\xampp\htdocs\api\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 D:\xampp\htdocs\api\index.php(37): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2022-05-09 11:52:47 --> There is no data to insert.
#0 D:\xampp\htdocs\api\system\BaseModel.php(718): CodeIgniter\Database\Exceptions\DataException::forEmptyDataset('insert')
#1 D:\xampp\htdocs\api\system\Model.php(620): CodeIgniter\BaseModel->insert(Array, true)
#2 D:\xampp\htdocs\api\app\Controllers\UserController.php(76): CodeIgniter\Model->insert(Array)
#3 D:\xampp\htdocs\api\system\CodeIgniter.php(824): App\Controllers\UserController->insertdata()
#4 D:\xampp\htdocs\api\system\CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UserController))
#5 D:\xampp\htdocs\api\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 D:\xampp\htdocs\api\index.php(37): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2022-05-09 11:53:47 --> There is no data to insert.
#0 D:\xampp\htdocs\api\system\BaseModel.php(718): CodeIgniter\Database\Exceptions\DataException::forEmptyDataset('insert')
#1 D:\xampp\htdocs\api\system\Model.php(620): CodeIgniter\BaseModel->insert(Array, true)
#2 D:\xampp\htdocs\api\app\Controllers\UserController.php(77): CodeIgniter\Model->insert(Array)
#3 D:\xampp\htdocs\api\system\CodeIgniter.php(824): App\Controllers\UserController->insertdata()
#4 D:\xampp\htdocs\api\system\CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UserController))
#5 D:\xampp\htdocs\api\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 D:\xampp\htdocs\api\index.php(37): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2022-05-09 11:53:51 --> There is no data to insert.
#0 D:\xampp\htdocs\api\system\BaseModel.php(718): CodeIgniter\Database\Exceptions\DataException::forEmptyDataset('insert')
#1 D:\xampp\htdocs\api\system\Model.php(620): CodeIgniter\BaseModel->insert(Array, true)
#2 D:\xampp\htdocs\api\app\Controllers\UserController.php(77): CodeIgniter\Model->insert(Array)
#3 D:\xampp\htdocs\api\system\CodeIgniter.php(824): App\Controllers\UserController->insertdata()
#4 D:\xampp\htdocs\api\system\CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UserController))
#5 D:\xampp\htdocs\api\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 D:\xampp\htdocs\api\index.php(37): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2022-05-09 11:54:47 --> There is no data to insert.
#0 D:\xampp\htdocs\api\system\BaseModel.php(718): CodeIgniter\Database\Exceptions\DataException::forEmptyDataset('insert')
#1 D:\xampp\htdocs\api\system\Model.php(620): CodeIgniter\BaseModel->insert(Array, true)
#2 D:\xampp\htdocs\api\app\Controllers\UserController.php(77): CodeIgniter\Model->insert(Array)
#3 D:\xampp\htdocs\api\system\CodeIgniter.php(824): App\Controllers\UserController->insertdata()
#4 D:\xampp\htdocs\api\system\CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UserController))
#5 D:\xampp\htdocs\api\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 D:\xampp\htdocs\api\index.php(37): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2022-05-09 11:54:51 --> There is no data to insert.
#0 D:\xampp\htdocs\api\system\BaseModel.php(718): CodeIgniter\Database\Exceptions\DataException::forEmptyDataset('insert')
#1 D:\xampp\htdocs\api\system\Model.php(620): CodeIgniter\BaseModel->insert(Array, true)
#2 D:\xampp\htdocs\api\app\Controllers\UserController.php(77): CodeIgniter\Model->insert(Array)
#3 D:\xampp\htdocs\api\system\CodeIgniter.php(824): App\Controllers\UserController->insertdata()
#4 D:\xampp\htdocs\api\system\CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UserController))
#5 D:\xampp\htdocs\api\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 D:\xampp\htdocs\api\index.php(37): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2022-05-09 11:55:57 --> There is no data to insert.
#0 D:\xampp\htdocs\api\system\BaseModel.php(718): CodeIgniter\Database\Exceptions\DataException::forEmptyDataset('insert')
#1 D:\xampp\htdocs\api\system\Model.php(620): CodeIgniter\BaseModel->insert(Array, true)
#2 D:\xampp\htdocs\api\app\Controllers\UserController.php(77): CodeIgniter\Model->insert(Array)
#3 D:\xampp\htdocs\api\system\CodeIgniter.php(824): App\Controllers\UserController->insertdata()
#4 D:\xampp\htdocs\api\system\CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UserController))
#5 D:\xampp\htdocs\api\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 D:\xampp\htdocs\api\index.php(37): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2022-05-09 12:00:49 --> There is no data to insert.
#0 D:\xampp\htdocs\api\system\BaseModel.php(718): CodeIgniter\Database\Exceptions\DataException::forEmptyDataset('insert')
#1 D:\xampp\htdocs\api\system\Model.php(620): CodeIgniter\BaseModel->insert(Array, true)
#2 D:\xampp\htdocs\api\app\Controllers\UserController.php(78): CodeIgniter\Model->insert(Array)
#3 D:\xampp\htdocs\api\system\CodeIgniter.php(824): App\Controllers\UserController->insertdata()
#4 D:\xampp\htdocs\api\system\CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UserController))
#5 D:\xampp\htdocs\api\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 D:\xampp\htdocs\api\index.php(37): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2022-05-09 12:02:04 --> There is no data to insert.
#0 D:\xampp\htdocs\api\system\BaseModel.php(718): CodeIgniter\Database\Exceptions\DataException::forEmptyDataset('insert')
#1 D:\xampp\htdocs\api\system\Model.php(620): CodeIgniter\BaseModel->insert(Array, true)
#2 D:\xampp\htdocs\api\app\Controllers\UserController.php(78): CodeIgniter\Model->insert(Array)
#3 D:\xampp\htdocs\api\system\CodeIgniter.php(824): App\Controllers\UserController->insertdata()
#4 D:\xampp\htdocs\api\system\CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UserController))
#5 D:\xampp\htdocs\api\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 D:\xampp\htdocs\api\index.php(37): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2022-05-09 12:02:11 --> There is no data to insert.
#0 D:\xampp\htdocs\api\system\BaseModel.php(718): CodeIgniter\Database\Exceptions\DataException::forEmptyDataset('insert')
#1 D:\xampp\htdocs\api\system\Model.php(620): CodeIgniter\BaseModel->insert(Array, true)
#2 D:\xampp\htdocs\api\app\Controllers\UserController.php(78): CodeIgniter\Model->insert(Array)
#3 D:\xampp\htdocs\api\system\CodeIgniter.php(824): App\Controllers\UserController->insertdata()
#4 D:\xampp\htdocs\api\system\CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UserController))
#5 D:\xampp\htdocs\api\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 D:\xampp\htdocs\api\index.php(37): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2022-05-09 12:02:14 --> There is no data to insert.
#0 D:\xampp\htdocs\api\system\BaseModel.php(718): CodeIgniter\Database\Exceptions\DataException::forEmptyDataset('insert')
#1 D:\xampp\htdocs\api\system\Model.php(620): CodeIgniter\BaseModel->insert(Array, true)
#2 D:\xampp\htdocs\api\app\Controllers\UserController.php(78): CodeIgniter\Model->insert(Array)
#3 D:\xampp\htdocs\api\system\CodeIgniter.php(824): App\Controllers\UserController->insertdata()
#4 D:\xampp\htdocs\api\system\CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UserController))
#5 D:\xampp\htdocs\api\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 D:\xampp\htdocs\api\index.php(37): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2022-05-09 12:02:22 --> There is no data to insert.
#0 D:\xampp\htdocs\api\system\BaseModel.php(718): CodeIgniter\Database\Exceptions\DataException::forEmptyDataset('insert')
#1 D:\xampp\htdocs\api\system\Model.php(620): CodeIgniter\BaseModel->insert(Array, true)
#2 D:\xampp\htdocs\api\app\Controllers\UserController.php(78): CodeIgniter\Model->insert(Array)
#3 D:\xampp\htdocs\api\system\CodeIgniter.php(824): App\Controllers\UserController->insertdata()
#4 D:\xampp\htdocs\api\system\CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UserController))
#5 D:\xampp\htdocs\api\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 D:\xampp\htdocs\api\index.php(37): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2022-05-09 12:03:08 --> There is no data to insert.
#0 D:\xampp\htdocs\api\system\BaseModel.php(718): CodeIgniter\Database\Exceptions\DataException::forEmptyDataset('insert')
#1 D:\xampp\htdocs\api\system\Model.php(620): CodeIgniter\BaseModel->insert(Array, true)
#2 D:\xampp\htdocs\api\app\Controllers\UserController.php(78): CodeIgniter\Model->insert(Array)
#3 D:\xampp\htdocs\api\system\CodeIgniter.php(824): App\Controllers\UserController->insertdata()
#4 D:\xampp\htdocs\api\system\CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UserController))
#5 D:\xampp\htdocs\api\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 D:\xampp\htdocs\api\index.php(37): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2022-05-09 12:03:12 --> There is no data to insert.
#0 D:\xampp\htdocs\api\system\BaseModel.php(718): CodeIgniter\Database\Exceptions\DataException::forEmptyDataset('insert')
#1 D:\xampp\htdocs\api\system\Model.php(620): CodeIgniter\BaseModel->insert(Array, true)
#2 D:\xampp\htdocs\api\app\Controllers\UserController.php(78): CodeIgniter\Model->insert(Array)
#3 D:\xampp\htdocs\api\system\CodeIgniter.php(824): App\Controllers\UserController->insertdata()
#4 D:\xampp\htdocs\api\system\CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UserController))
#5 D:\xampp\htdocs\api\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 D:\xampp\htdocs\api\index.php(37): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2022-05-09 12:03:56 --> There is no data to insert.
#0 D:\xampp\htdocs\api\system\BaseModel.php(718): CodeIgniter\Database\Exceptions\DataException::forEmptyDataset('insert')
#1 D:\xampp\htdocs\api\system\Model.php(620): CodeIgniter\BaseModel->insert(Array, true)
#2 D:\xampp\htdocs\api\app\Controllers\UserController.php(78): CodeIgniter\Model->insert(Array)
#3 D:\xampp\htdocs\api\system\CodeIgniter.php(824): App\Controllers\UserController->insertdata()
#4 D:\xampp\htdocs\api\system\CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UserController))
#5 D:\xampp\htdocs\api\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 D:\xampp\htdocs\api\index.php(37): CodeIgniter\CodeIgniter->run()
#7 {main}
ERROR - 2022-05-09 12:05:55 --> Column 'users_password' cannot be null
CRITICAL - 2022-05-09 12:09:32 --> Call to a member function getVar() on null
#0 D:\xampp\htdocs\api\system\CodeIgniter.php(824): App\Controllers\UserController->insertdata()
#1 D:\xampp\htdocs\api\system\CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UserController))
#2 D:\xampp\htdocs\api\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 D:\xampp\htdocs\api\index.php(37): CodeIgniter\CodeIgniter->run()
#4 {main}
CRITICAL - 2022-05-09 12:09:58 --> syntax error, unexpected '->' (T_OBJECT_OPERATOR), expecting ')'
#0 D:\xampp\htdocs\api\system\Autoloader\Autoloader.php(241): CodeIgniter\Autoloader\Autoloader->includeFile('D:\\xampp\\htdocs...')
#1 D:\xampp\htdocs\api\system\Autoloader\Autoloader.php(219): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Controllers...')
#2 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Controllers...')
#3 [internal function]: spl_autoload_call('App\\Controllers...')
#4 D:\xampp\htdocs\api\system\CodeIgniter.php(789): class_exists('\\App\\Controller...', true)
#5 D:\xampp\htdocs\api\system\CodeIgniter.php(397): CodeIgniter\CodeIgniter->startController()
#6 D:\xampp\htdocs\api\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\xampp\htdocs\api\index.php(37): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2022-05-09 12:17:59 --> Call to undefined function App\Controllers\encrypt()
#0 D:\xampp\htdocs\api\system\CodeIgniter.php(824): App\Controllers\UserController->insertdata()
#1 D:\xampp\htdocs\api\system\CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UserController))
#2 D:\xampp\htdocs\api\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 D:\xampp\htdocs\api\index.php(37): CodeIgniter\CodeIgniter->run()
#4 {main}
CRITICAL - 2022-05-09 12:18:13 --> Call to undefined function App\Controllers\encrypt()
#0 D:\xampp\htdocs\api\system\CodeIgniter.php(824): App\Controllers\UserController->insertdata()
#1 D:\xampp\htdocs\api\system\CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UserController))
#2 D:\xampp\htdocs\api\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 D:\xampp\htdocs\api\index.php(37): CodeIgniter\CodeIgniter->run()
#4 {main}
CRITICAL - 2022-05-09 12:32:31 --> syntax error, unexpected 'function' (T_FUNCTION)
#0 D:\xampp\htdocs\api\system\Autoloader\Autoloader.php(241): CodeIgniter\Autoloader\Autoloader->includeFile('D:\\xampp\\htdocs...')
#1 D:\xampp\htdocs\api\system\Autoloader\Autoloader.php(219): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Controllers...')
#2 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Controllers...')
#3 [internal function]: spl_autoload_call('App\\Controllers...')
#4 D:\xampp\htdocs\api\system\CodeIgniter.php(789): class_exists('\\App\\Controller...', true)
#5 D:\xampp\htdocs\api\system\CodeIgniter.php(397): CodeIgniter\CodeIgniter->startController()
#6 D:\xampp\htdocs\api\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\xampp\htdocs\api\index.php(37): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2022-05-09 12:33:11 --> syntax error, unexpected 'function' (T_FUNCTION)
#0 D:\xampp\htdocs\api\system\Autoloader\Autoloader.php(241): CodeIgniter\Autoloader\Autoloader->includeFile('D:\\xampp\\htdocs...')
#1 D:\xampp\htdocs\api\system\Autoloader\Autoloader.php(219): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Controllers...')
#2 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Controllers...')
#3 [internal function]: spl_autoload_call('App\\Controllers...')
#4 D:\xampp\htdocs\api\system\CodeIgniter.php(789): class_exists('\\App\\Controller...', true)
#5 D:\xampp\htdocs\api\system\CodeIgniter.php(397): CodeIgniter\CodeIgniter->startController()
#6 D:\xampp\htdocs\api\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\xampp\htdocs\api\index.php(37): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2022-05-09 12:33:23 --> syntax error, unexpected 'function' (T_FUNCTION)
#0 D:\xampp\htdocs\api\system\Autoloader\Autoloader.php(241): CodeIgniter\Autoloader\Autoloader->includeFile('D:\\xampp\\htdocs...')
#1 D:\xampp\htdocs\api\system\Autoloader\Autoloader.php(219): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Controllers...')
#2 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Controllers...')
#3 [internal function]: spl_autoload_call('App\\Controllers...')
#4 D:\xampp\htdocs\api\system\CodeIgniter.php(789): class_exists('\\App\\Controller...', true)
#5 D:\xampp\htdocs\api\system\CodeIgniter.php(397): CodeIgniter\CodeIgniter->startController()
#6 D:\xampp\htdocs\api\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\xampp\htdocs\api\index.php(37): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2022-05-09 12:33:27 --> syntax error, unexpected 'function' (T_FUNCTION)
#0 D:\xampp\htdocs\api\system\Autoloader\Autoloader.php(241): CodeIgniter\Autoloader\Autoloader->includeFile('D:\\xampp\\htdocs...')
#1 D:\xampp\htdocs\api\system\Autoloader\Autoloader.php(219): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Controllers...')
#2 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Controllers...')
#3 [internal function]: spl_autoload_call('App\\Controllers...')
#4 D:\xampp\htdocs\api\system\CodeIgniter.php(789): class_exists('\\App\\Controller...', true)
#5 D:\xampp\htdocs\api\system\CodeIgniter.php(397): CodeIgniter\CodeIgniter->startController()
#6 D:\xampp\htdocs\api\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\xampp\htdocs\api\index.php(37): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2022-05-09 12:33:50 --> syntax error, unexpected 'function' (T_FUNCTION)
#0 D:\xampp\htdocs\api\system\Autoloader\Autoloader.php(241): CodeIgniter\Autoloader\Autoloader->includeFile('D:\\xampp\\htdocs...')
#1 D:\xampp\htdocs\api\system\Autoloader\Autoloader.php(219): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Controllers...')
#2 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Controllers...')
#3 [internal function]: spl_autoload_call('App\\Controllers...')
#4 D:\xampp\htdocs\api\system\CodeIgniter.php(789): class_exists('\\App\\Controller...', true)
#5 D:\xampp\htdocs\api\system\CodeIgniter.php(397): CodeIgniter\CodeIgniter->startController()
#6 D:\xampp\htdocs\api\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\xampp\htdocs\api\index.php(37): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2022-05-09 12:41:53 --> syntax error, unexpected 'public' (T_PUBLIC), expecting end of file
#0 D:\xampp\htdocs\api\system\Autoloader\Autoloader.php(241): CodeIgniter\Autoloader\Autoloader->includeFile('D:\\xampp\\htdocs...')
#1 D:\xampp\htdocs\api\system\Autoloader\Autoloader.php(219): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Controllers...')
#2 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Controllers...')
#3 [internal function]: spl_autoload_call('App\\Controllers...')
#4 D:\xampp\htdocs\api\system\CodeIgniter.php(789): class_exists('\\App\\Controller...', true)
#5 D:\xampp\htdocs\api\system\CodeIgniter.php(397): CodeIgniter\CodeIgniter->startController()
#6 D:\xampp\htdocs\api\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\xampp\htdocs\api\index.php(37): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2022-05-09 12:41:56 --> syntax error, unexpected 'public' (T_PUBLIC), expecting end of file
#0 D:\xampp\htdocs\api\system\Autoloader\Autoloader.php(241): CodeIgniter\Autoloader\Autoloader->includeFile('D:\\xampp\\htdocs...')
#1 D:\xampp\htdocs\api\system\Autoloader\Autoloader.php(219): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Controllers...')
#2 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Controllers...')
#3 [internal function]: spl_autoload_call('App\\Controllers...')
#4 D:\xampp\htdocs\api\system\CodeIgniter.php(789): class_exists('\\App\\Controller...', true)
#5 D:\xampp\htdocs\api\system\CodeIgniter.php(397): CodeIgniter\CodeIgniter->startController()
#6 D:\xampp\htdocs\api\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\xampp\htdocs\api\index.php(37): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2022-05-09 12:42:00 --> syntax error, unexpected 'public' (T_PUBLIC), expecting end of file
#0 D:\xampp\htdocs\api\system\Autoloader\Autoloader.php(241): CodeIgniter\Autoloader\Autoloader->includeFile('D:\\xampp\\htdocs...')
#1 D:\xampp\htdocs\api\system\Autoloader\Autoloader.php(219): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Controllers...')
#2 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Controllers...')
#3 [internal function]: spl_autoload_call('App\\Controllers...')
#4 D:\xampp\htdocs\api\system\CodeIgniter.php(789): class_exists('\\App\\Controller...', true)
#5 D:\xampp\htdocs\api\system\CodeIgniter.php(397): CodeIgniter\CodeIgniter->startController()
#6 D:\xampp\htdocs\api\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\xampp\htdocs\api\index.php(37): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2022-05-09 12:43:29 --> syntax error, unexpected 'public' (T_PUBLIC), expecting end of file
#0 D:\xampp\htdocs\api\system\Autoloader\Autoloader.php(241): CodeIgniter\Autoloader\Autoloader->includeFile('D:\\xampp\\htdocs...')
#1 D:\xampp\htdocs\api\system\Autoloader\Autoloader.php(219): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Controllers...')
#2 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Controllers...')
#3 [internal function]: spl_autoload_call('App\\Controllers...')
#4 D:\xampp\htdocs\api\system\CodeIgniter.php(789): class_exists('\\App\\Controller...', true)
#5 D:\xampp\htdocs\api\system\CodeIgniter.php(397): CodeIgniter\CodeIgniter->startController()
#6 D:\xampp\htdocs\api\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\xampp\htdocs\api\index.php(37): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2022-05-09 12:43:55 --> password_hash() expects at least 2 parameters, 1 given
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'password_hash()...', 'D:\\xampp\\htdocs...', 22, Array)
#1 D:\xampp\htdocs\api\app\Controllers\UserController.php(22): password_hash('india55555')
#2 D:\xampp\htdocs\api\system\CodeIgniter.php(824): App\Controllers\UserController->signUpUser()
#3 D:\xampp\htdocs\api\system\CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UserController))
#4 D:\xampp\htdocs\api\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 D:\xampp\htdocs\api\index.php(37): CodeIgniter\CodeIgniter->run()
#6 {main}
CRITICAL - 2022-05-09 12:46:03 --> syntax error, unexpected 'public' (T_PUBLIC), expecting end of file
#0 D:\xampp\htdocs\api\system\Autoloader\Autoloader.php(241): CodeIgniter\Autoloader\Autoloader->includeFile('D:\\xampp\\htdocs...')
#1 D:\xampp\htdocs\api\system\Autoloader\Autoloader.php(219): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Controllers...')
#2 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Controllers...')
#3 [internal function]: spl_autoload_call('App\\Controllers...')
#4 D:\xampp\htdocs\api\system\CodeIgniter.php(789): class_exists('\\App\\Controller...', true)
#5 D:\xampp\htdocs\api\system\CodeIgniter.php(397): CodeIgniter\CodeIgniter->startController()
#6 D:\xampp\htdocs\api\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\xampp\htdocs\api\index.php(37): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2022-05-09 12:46:54 --> syntax error, unexpected 'public' (T_PUBLIC), expecting end of file
#0 D:\xampp\htdocs\api\system\Autoloader\Autoloader.php(241): CodeIgniter\Autoloader\Autoloader->includeFile('D:\\xampp\\htdocs...')
#1 D:\xampp\htdocs\api\system\Autoloader\Autoloader.php(219): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Controllers...')
#2 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Controllers...')
#3 [internal function]: spl_autoload_call('App\\Controllers...')
#4 D:\xampp\htdocs\api\system\CodeIgniter.php(789): class_exists('\\App\\Controller...', true)
#5 D:\xampp\htdocs\api\system\CodeIgniter.php(397): CodeIgniter\CodeIgniter->startController()
#6 D:\xampp\htdocs\api\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\xampp\htdocs\api\index.php(37): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2022-05-09 12:47:56 --> syntax error, unexpected 'public' (T_PUBLIC), expecting end of file
#0 D:\xampp\htdocs\api\system\Autoloader\Autoloader.php(241): CodeIgniter\Autoloader\Autoloader->includeFile('D:\\xampp\\htdocs...')
#1 D:\xampp\htdocs\api\system\Autoloader\Autoloader.php(219): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Controllers...')
#2 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Controllers...')
#3 [internal function]: spl_autoload_call('App\\Controllers...')
#4 D:\xampp\htdocs\api\system\CodeIgniter.php(789): class_exists('\\App\\Controller...', true)
#5 D:\xampp\htdocs\api\system\CodeIgniter.php(397): CodeIgniter\CodeIgniter->startController()
#6 D:\xampp\htdocs\api\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\xampp\htdocs\api\index.php(37): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2022-05-09 12:48:45 --> syntax error, unexpected 'public' (T_PUBLIC), expecting end of file
#0 D:\xampp\htdocs\api\system\Autoloader\Autoloader.php(241): CodeIgniter\Autoloader\Autoloader->includeFile('D:\\xampp\\htdocs...')
#1 D:\xampp\htdocs\api\system\Autoloader\Autoloader.php(219): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Controllers...')
#2 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Controllers...')
#3 [internal function]: spl_autoload_call('App\\Controllers...')
#4 D:\xampp\htdocs\api\system\CodeIgniter.php(789): class_exists('\\App\\Controller...', true)
#5 D:\xampp\htdocs\api\system\CodeIgniter.php(397): CodeIgniter\CodeIgniter->startController()
#6 D:\xampp\htdocs\api\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\xampp\htdocs\api\index.php(37): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2022-05-09 12:48:47 --> syntax error, unexpected 'public' (T_PUBLIC), expecting end of file
#0 D:\xampp\htdocs\api\system\Autoloader\Autoloader.php(241): CodeIgniter\Autoloader\Autoloader->includeFile('D:\\xampp\\htdocs...')
#1 D:\xampp\htdocs\api\system\Autoloader\Autoloader.php(219): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Controllers...')
#2 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Controllers...')
#3 [internal function]: spl_autoload_call('App\\Controllers...')
#4 D:\xampp\htdocs\api\system\CodeIgniter.php(789): class_exists('\\App\\Controller...', true)
#5 D:\xampp\htdocs\api\system\CodeIgniter.php(397): CodeIgniter\CodeIgniter->startController()
#6 D:\xampp\htdocs\api\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\xampp\htdocs\api\index.php(37): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2022-05-09 12:48:59 --> syntax error, unexpected 'public' (T_PUBLIC), expecting end of file
#0 D:\xampp\htdocs\api\system\Autoloader\Autoloader.php(241): CodeIgniter\Autoloader\Autoloader->includeFile('D:\\xampp\\htdocs...')
#1 D:\xampp\htdocs\api\system\Autoloader\Autoloader.php(219): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Controllers...')
#2 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Controllers...')
#3 [internal function]: spl_autoload_call('App\\Controllers...')
#4 D:\xampp\htdocs\api\system\CodeIgniter.php(789): class_exists('\\App\\Controller...', true)
#5 D:\xampp\htdocs\api\system\CodeIgniter.php(397): CodeIgniter\CodeIgniter->startController()
#6 D:\xampp\htdocs\api\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\xampp\htdocs\api\index.php(37): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2022-05-09 12:50:35 --> Namespace declaration statement has to be the very first statement or after any declare call in the script
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2022-05-09 12:50:51 --> Namespace declaration statement has to be the very first statement or after any declare call in the script
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2022-05-09 12:50:52 --> Namespace declaration statement has to be the very first statement or after any declare call in the script
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2022-05-09 12:51:04 --> Namespace declaration statement has to be the very first statement or after any declare call in the script
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2022-05-09 12:52:33 --> password_hash() expects at least 2 parameters, 1 given
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'password_hash()...', 'D:\\xampp\\htdocs...', 23, Array)
#1 D:\xampp\htdocs\api\app\Controllers\UserController.php(23): password_hash('india55555')
#2 D:\xampp\htdocs\api\system\CodeIgniter.php(824): App\Controllers\UserController->registerUser()
#3 D:\xampp\htdocs\api\system\CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UserController))
#4 D:\xampp\htdocs\api\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 D:\xampp\htdocs\api\index.php(37): CodeIgniter\CodeIgniter->run()
#6 {main}
CRITICAL - 2022-05-09 12:52:46 --> password_hash() expects at least 2 parameters, 1 given
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'password_hash()...', 'D:\\xampp\\htdocs...', 23, Array)
#1 D:\xampp\htdocs\api\app\Controllers\UserController.php(23): password_hash('india55555')
#2 D:\xampp\htdocs\api\system\CodeIgniter.php(824): App\Controllers\UserController->registerUser()
#3 D:\xampp\htdocs\api\system\CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UserController))
#4 D:\xampp\htdocs\api\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 D:\xampp\htdocs\api\index.php(37): CodeIgniter\CodeIgniter->run()
#6 {main}
CRITICAL - 2022-05-09 12:53:00 --> password_hash() expects at least 2 parameters, 1 given
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'password_hash()...', 'D:\\xampp\\htdocs...', 23, Array)
#1 D:\xampp\htdocs\api\app\Controllers\UserController.php(23): password_hash('india55555')
#2 D:\xampp\htdocs\api\system\CodeIgniter.php(824): App\Controllers\UserController->registerUser()
#3 D:\xampp\htdocs\api\system\CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UserController))
#4 D:\xampp\htdocs\api\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 D:\xampp\htdocs\api\index.php(37): CodeIgniter\CodeIgniter->run()
#6 {main}
CRITICAL - 2022-05-09 12:53:29 --> password_hash() expects at least 2 parameters, 1 given
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'password_hash()...', 'D:\\xampp\\htdocs...', 23, Array)
#1 D:\xampp\htdocs\api\app\Controllers\UserController.php(23): password_hash('india55555')
#2 D:\xampp\htdocs\api\system\CodeIgniter.php(824): App\Controllers\UserController->registerUser()
#3 D:\xampp\htdocs\api\system\CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UserController))
#4 D:\xampp\htdocs\api\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 D:\xampp\htdocs\api\index.php(37): CodeIgniter\CodeIgniter->run()
#6 {main}
CRITICAL - 2022-05-09 12:53:46 --> password_hash() expects at least 2 parameters, 1 given
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'password_hash()...', 'D:\\xampp\\htdocs...', 23, Array)
#1 D:\xampp\htdocs\api\app\Controllers\UserController.php(23): password_hash('123456567577')
#2 D:\xampp\htdocs\api\system\CodeIgniter.php(824): App\Controllers\UserController->registerUser()
#3 D:\xampp\htdocs\api\system\CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UserController))
#4 D:\xampp\htdocs\api\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 D:\xampp\htdocs\api\index.php(37): CodeIgniter\CodeIgniter->run()
#6 {main}
